"use client";
import {FormEvent,useEffect,useState} from "react";import {useParams} from "next/navigation";import {restoreWebSession,webApi} from "../../auth/session";
type Item={type:string;title?:string;notes?:string;startLocalTime?:string;endLocalTime?:string;allDay?:boolean;plannedAmount?:string;plannedCurrency?:string;accommodationId?:string;restaurantId?:string;activityId?:string;attractionId?:string;placeId?:string;transportLegId?:string};type Day={id:string;date?:string;items?:Item[]};
type Trip={id:string;ownerId?:string;relationship?:"OWNED"|"MEMBER";title:string;startDate:string;endDate:string;primaryCurrency:string;travelerCount:number;version:number;status:string;days?:Day[];destinations?:Array<{destination?:{id?:string;canonicalSlug?:string};destinationId?:string;destinationSlug?:string;arrivalDate?:string;departureDate?:string;notes?:string}>;transportLegs?:Array<{mode:string;fromLabel:string;toLabel:string;fromDestinationId?:string;toDestinationId?:string;plannedDate?:string;plannedAmount?:string;plannedCurrency?:string;notes?:string}>};
type Member={id:string;userId?:string;role:"EDITOR"|"VIEWER";user?:{id?:string;displayName?:string;email?:string}};
type Estimate={estimates?:Array<{id:string;scenario:string;currency:string;totalAmount:string;completeness?:string;confidence?:string;unknownCount?:number}>};
export default function TripDetail(){const {id}=useParams<{id:string}>(),[trip,setTrip]=useState<Trip|null>(null),[estimate,setEstimate]=useState<Estimate>(),[members,setMembers]=useState<Member[]>([]),[status,setStatus]=useState("Đang tải kế hoạch…"),[userId,setUserId]=useState<string>();
async function load(){const user=await restoreWebSession();if(!user){location.assign("/auth/login");return}setUserId(user.id);try{const [value,memberValue]=await Promise.all([webApi.trip<Trip>(id),webApi.tripMembers<Member[]>(id).catch(()=>[])]);setTrip(value);setMembers(Array.isArray(memberValue)?memberValue:[]);setStatus("");try{setEstimate((await webApi.latestTripEstimate<Estimate|null>(id))??undefined)}catch{setEstimate(undefined)}}catch{setStatus("Không thể tải chuyến đi hoặc bạn không có quyền truy cập.")}}
useEffect(()=>{void load()},[id]);
async function destinations(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!trip)return;const f=new FormData(e.currentTarget),slug=String(f.get("slug")||"").trim();try{const existing=(trip.destinations??[]).map(d=>({destinationSlug:d.destination?.canonicalSlug??d.destination?.id??d.destinationSlug??d.destinationId,arrivalDate:d.arrivalDate?.slice(0,10),departureDate:d.departureDate?.slice(0,10),notes:d.notes})).filter(d=>d.destinationSlug);await webApi.replaceTripDestinations(id,trip.version,[...existing,{destinationSlug:slug,arrivalDate:String(f.get("arrival")||"")||undefined,departureDate:String(f.get("departure")||"")||undefined}]);setStatus("Đã cập nhật điểm đến.");await load()}catch{setStatus("Không thể cập nhật điểm đến. Hãy tải lại nếu kế hoạch vừa được người khác sửa.")}}
async function transport(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!trip)return;const f=new FormData(e.currentTarget);try{const existing=(trip.transportLegs??[]).map(x=>({mode:x.mode,fromLabel:x.fromLabel,toLabel:x.toLabel,fromDestinationSlug:x.fromDestinationId,toDestinationSlug:x.toDestinationId,plannedDate:x.plannedDate?.slice(0,10),plannedAmount:x.plannedAmount?String(x.plannedAmount):undefined,plannedCurrency:x.plannedCurrency,notes:x.notes}));await webApi.replaceTripTransportLegs(id,trip.version,[...existing,{mode:String(f.get("mode")),fromLabel:String(f.get("from")),toLabel:String(f.get("to")),plannedDate:String(f.get("date")||"")||undefined,plannedAmount:String(f.get("amount")||"")||undefined,plannedCurrency:trip.primaryCurrency}]);setStatus("Đã cập nhật chặng di chuyển.");await load()}catch{setStatus("Không thể cập nhật chặng di chuyển.")}}
async function dayItem(e:FormEvent<HTMLFormElement>,dayId:string){e.preventDefault();if(!trip)return;const f=new FormData(e.currentTarget);try{const day=trip.days?.find(d=>d.id===dayId);const existing=(day?.items??[]).map(x=>({type:x.type,title:x.title,notes:x.notes,startLocalTime:x.startLocalTime,endLocalTime:x.endLocalTime,allDay:x.allDay,plannedAmount:x.plannedAmount?String(x.plannedAmount):undefined,plannedCurrency:x.plannedCurrency,accommodationSlug:x.accommodationId,restaurantSlug:x.restaurantId,activitySlug:x.activityId,attractionSlug:x.attractionId,placeSlug:x.placeId,transportLegId:x.transportLegId}));await webApi.replaceTripDayItems(id,dayId,trip.version,[...existing,{type:"CUSTOM",title:String(f.get("title")),startLocalTime:String(f.get("time")||"")||undefined,plannedAmount:String(f.get("amount")||"")||undefined,plannedCurrency:trip.primaryCurrency}]);setStatus("Đã cập nhật lịch trình.");await load()}catch{setStatus("Không thể cập nhật lịch trình.")}}
async function invite(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);try{await webApi.inviteTripMember(id,String(f.get("email")),String(f.get("role")) as "EDITOR"|"VIEWER");setStatus("Đã gửi lời mời.");e.currentTarget.reset()}catch{setStatus("Không thể gửi lời mời. Chỉ chủ chuyến đi có quyền quản lý thành viên.")}}
if(!trip)return <main id="main" className="auth-shell"><p role="status">{status}</p></main>;
const role=trip.ownerId===userId?"OWNER":members.find(m=>m.userId===userId||m.user?.id===userId)?.role;const canEdit=role==="OWNER"||role==="EDITOR";const canManage=role==="OWNER";
return <main id="main" className="auth-shell"><section className="auth-card"><a href="/trips">← Tất cả chuyến đi</a><p className="eyebrow">PLAN</p><h1>{trip.title}</h1><p>{trip.startDate} → {trip.endDate} · {trip.travelerCount} người · {trip.primaryCurrency}</p><p>Trạng thái: {trip.status} · phiên bản kế hoạch {trip.version}</p>
<h2>Điểm đến</h2>{trip.destinations?.length?trip.destinations.map((d,i)=><p key={i}>{d.destination?.canonicalSlug??d.destinationSlug??"Điểm đến"}{d.arrivalDate?" · "+d.arrivalDate:""}{d.departureDate?" → "+d.departureDate:""}</p>):<p>Chưa có điểm đến.</p>}{canEdit&&<form className="auth-form" onSubmit={destinations}><label>Destination slug<input name="slug" required placeholder="kyoto"/></label><label>Đến<input name="arrival" type="date"/></label><label>Rời đi<input name="departure" type="date"/></label><button className="button button-quiet">Lưu điểm đến</button></form>}
<h2>Lịch trình</h2>{trip.days?.length?trip.days.map(d=><article key={d.id}><h3>{d.date??"Ngày trong chuyến đi"}</h3><p>{d.items?.length??0} hoạt động</p>{canEdit&&<form className="auth-form" onSubmit={e=>dayItem(e,d.id)}><label>Hoạt động tùy chỉnh<input name="title" required/></label><label>Giờ bắt đầu<input name="time" type="time"/></label><label>Chi phí dự kiến<input name="amount" inputMode="decimal"/></label><button className="button button-quiet">Lưu hoạt động ngày này</button></form>}</article>):<p>Chưa có ngày lịch trình từ API.</p>}
<h2>Di chuyển</h2>{trip.transportLegs?.length?trip.transportLegs.map((leg,i)=><p key={i}>{leg.fromLabel} → {leg.toLabel} · {leg.mode}</p>):<p>Chưa có chặng di chuyển.</p>}{canEdit&&<form className="auth-form" onSubmit={transport}><label>Phương tiện<select name="mode" defaultValue="TRAIN"><option>TRAIN</option><option>BUS</option><option>CAR</option><option>FLIGHT</option><option>FERRY</option><option>WALK</option><option>OTHER</option></select></label><label>Từ<input name="from" required/></label><label>Đến<input name="to" required/></label><label>Ngày<input name="date" type="date"/></label><label>Chi phí dự kiến<input name="amount" inputMode="decimal"/></label><button className="button button-quiet">Lưu chặng</button></form>}
<h2>Ước tính chi phí</h2>{estimate?.estimates?.length?estimate.estimates.map(x=><article key={x.id}><h3>{x.scenario}</h3><p>{x.totalAmount} {x.currency}</p><p>Độ đầy đủ: {x.completeness??"—"} · Độ tin cậy: {x.confidence??"—"} · Chưa biết: {x.unknownCount??0}</p></article>):<p>Chưa có ước tính. Hệ thống không tự bịa số khi thiếu dữ liệu.</p>}{canEdit&&<button className="button button-gold" onClick={async()=>{setStatus("Đang tính lại…");try{setEstimate(await webApi.generateTripEstimate<Estimate>(id));setStatus("Đã tạo ước tính mới.")}catch{setStatus("Chưa đủ dữ liệu hoặc bạn không có quyền tạo ước tính.")}}}>Tính lại chi phí</button>}
<h2>Cộng tác</h2>{members.length?members.map(m=><p key={m.id}>{m.user?.displayName||m.user?.email||m.userId||"Thành viên"} · {m.role}</p>):<p>Chưa có thành viên khác hoặc tài khoản hiện tại không có quyền xem.</p>}{canManage&&<form className="auth-form" onSubmit={invite}><label>Email<input name="email" type="email" required/></label><label>Vai trò<select name="role" defaultValue="EDITOR"><option value="EDITOR">EDITOR — có thể sửa kế hoạch</option><option value="VIEWER">VIEWER — chỉ xem</option></select></label><button className="button button-quiet">Mời cộng tác</button></form>}
{status&&<p role="status">{status}</p>}</section></main>}