import {useCallback,useEffect,useState} from "react";
import {Pressable,StyleSheet,Text,TextInput,View} from "react-native";
import * as Location from "expo-location";
import {useLocalSearchParams,router} from "expo-router";
import {mobileApi} from "../../../src/auth/session";
import {useAuth} from "../../../src/auth/auth-context";
import {AppShell} from "../../../src/ui/app-shell";
import {ScreenState} from "../../../src/ui/screen-state";
type Member={id:string;userId:string;role:"EDITOR"|"VIEWER";user?:{id?:string;displayName?:string;email?:string}};
type Invite={id:string;email:string;role:string;status:string};
type Sharing={status:string;expiresAt?:string|null;locationAvailability?:string};
export default function Together(){const {id}=useLocalSearchParams<{id:string}>(),auth=useAuth(),[owner,setOwner]=useState(""),[version,setVersion]=useState(0),[members,setMembers]=useState<Member[]>([]),[invites,setInvites]=useState<Invite[]>([]),[activity,setActivity]=useState<any[]>([]),[sharing,setSharing]=useState<Sharing>(),[locations,setLocations]=useState<any[]>([]),[expenses,setExpenses]=useState<any[]>([]),[summary,setSummary]=useState<any>(),[suggestions,setSuggestions]=useState<any[]>([]),[settlements,setSettlements]=useState<any[]>([]),[email,setEmail]=useState(""),[inviteRole,setInviteRole]=useState<"EDITOR"|"VIEWER">("VIEWER"),[duration,setDuration]=useState("60"),[expenseTitle,setExpenseTitle]=useState(""),[expenseAmount,setExpenseAmount]=useState(""),[state,setState]=useState<"loading"|"error"|"success">("loading"),[message,setMessage]=useState("");
const role=owner===auth.user?.id?"OWNER":members.find(m=>m.userId===auth.user?.id||m.user?.id===auth.user?.id)?.role,canEdit=role==="OWNER"||role==="EDITOR",canManage=role==="OWNER";
const load=useCallback(async()=>{setState("loading");try{const trip=await mobileApi.trip<{ownerId:string;version:number}>(id);setOwner(trip.ownerId);setVersion(trip.version);const[m,a,s,l,e,sum,sug,sett]=await Promise.all([mobileApi.tripMembers<Member[]>(id),mobileApi.tripActivity<any>(id),mobileApi.myTripLocationSharing<Sharing>(id),mobileApi.tripLocations<any[]>(id),mobileApi.tripExpenses<any>(id),mobileApi.tripExpenseSummary<any>(id),mobileApi.tripSettlementSuggestions<any>(id),mobileApi.tripSettlements<any>(id)]);setMembers(m);setActivity(a.items??[]);setSharing(s);setLocations(l);setExpenses(e.items??[]);setSummary(sum);setSuggestions(sug.suggestionsByCurrency??[]);setSettlements(sett.items??[]);setInvites(trip.ownerId===auth.user?.id?await mobileApi.tripInvitations<Invite[]>(id):[]);setState("success")}catch{setState("error")}},[id,auth.user?.id]);useEffect(()=>{void load()},[load]);
async function safe(fn:()=>Promise<unknown>,ok:string){try{await fn();setMessage(ok);await load()}catch(e:any){setMessage(e?.code==="TRIP_VERSION_CONFLICT"?"Chuyến đi vừa thay đổi. Đã tải lại dữ liệu; hãy kiểm tra trước khi thử lại.":"Thao tác không thành công. Kiểm tra quyền và dữ liệu.");await load()}}
async function invite(){if(!canManage||!email.trim())return;await safe(()=>mobileApi.inviteTripMember(id,email.trim(),inviteRole),"Đã gửi lời mời.");setEmail("")}
async function start(){const n=Number(duration);if(!Number.isFinite(n)||n<1)return setMessage("Thời lượng phải lớn hơn 0 phút.");try{setSharing(await mobileApi.startTripLocationSharing<Sharing>(id,n));setMessage("Đã bật chia sẻ cho chính bạn. Chưa có tọa độ nào được gửi.")}catch{setMessage("Không thể bật chia sẻ vị trí.")}}
async function pushLocation(){if(sharing?.status!=="ACTIVE")return setMessage("Bạn phải tự bật chia sẻ trước khi gửi vị trí.");setMessage("Đang xin quyền vị trí từ thiết bị…");const permission=await Location.requestForegroundPermissionsAsync();if(permission.status!=="granted")return setMessage("Bạn đã không cấp quyền vị trí. Không có tọa độ nào được gửi.");try{const p=await Location.getCurrentPositionAsync({accuracy:Location.Accuracy.High});await safe(()=>mobileApi.updateTripLocation(id,{latitude:p.coords.latitude,longitude:p.coords.longitude,accuracyMeters:p.coords.accuracy??0,capturedAt:new Date(p.timestamp).toISOString()}),"Đã cập nhật vị trí hiện tại.")}catch{setMessage("Thiết bị không thể xác định vị trí. Không có tọa độ nào được gửi.")}}
async function addExpense(){if(!canEdit||!expenseTitle.trim()||!expenseAmount)return;await safe(()=>mobileApi.createTripExpense(id,{title:expenseTitle.trim(),category:"OTHER",amount:expenseAmount,currency:"VND",payerUserId:auth.user?.id,splitMode:"EQUAL",occurredOn:new Date().toISOString().slice(0,10),shares:[{userId:auth.user?.id}]}),"Đã ghi chi phí thực tế.");setExpenseTitle("");setExpenseAmount("")}
if(state==="loading")return <ScreenState kind="loading" title="Đang tải TOGETHER…"/>;if(state==="error")return <ScreenState kind="error" title="Không thể tải TOGETHER" detail="Kiểm tra quyền truy cập hoặc kết nối." onRetry={load}/>;
return <AppShell title="TOGETHER"><View style={s.body}><Pressable accessibilityRole="link" onPress={()=>router.push({pathname:"/trips/[id]",params:{id}})}><Text>← Kế hoạch</Text></Pressable><Text style={s.title}>Đi cùng nhau</Text><Text>Vai trò: {role??"—"}</Text>
<Text style={s.h2}>Thành viên</Text>{members.length?members.map(m=><View key={m.id} style={s.card}><Text>{m.user?.displayName||m.user?.email||m.userId} · {m.role}</Text>{canManage&&<View style={s.row}><Action label={"Đổi "+(m.role==="EDITOR"?"VIEWER":"EDITOR")} onPress={()=>safe(()=>mobileApi.updateTripMemberRole(id,m.id,m.role==="EDITOR"?"VIEWER":"EDITOR",version),"Đã đổi vai trò.")}/><Action label="Xóa" onPress={()=>safe(()=>mobileApi.removeTripMember(id,m.id,version),"Đã xóa thành viên.")}/><Action label="Chuyển chủ" onPress={()=>safe(()=>mobileApi.transferTripOwnership(id,m.userId,version),"Đã chuyển quyền sở hữu.")}/></View>}</View>):<Text>Chưa có thành viên khác.</Text>}{role&&role!=="OWNER"&&<Action label="Rời chuyến đi" onPress={()=>safe(()=>mobileApi.leaveTrip(id,version),"Đã rời chuyến đi.")}/>}
{canManage&&<View style={s.panel}><Text style={s.h2}>Lời mời</Text><TextInput accessibilityLabel="Email người được mời" value={email} onChangeText={setEmail} keyboardType="email-address" autoCapitalize="none" style={s.input}/><View style={s.row}><Action label={"Vai trò: "+inviteRole} onPress={()=>setInviteRole(x=>x==="VIEWER"?"EDITOR":"VIEWER")}/><Action label="Gửi lời mời" onPress={invite}/></View>{invites.map(x=><View key={x.id}><Text>{x.email} · {x.role} · {x.status}</Text>{x.status==="PENDING"&&<Action label="Thu hồi" onPress={()=>safe(()=>mobileApi.revokeTripInvitation(id,x.id),"Đã thu hồi lời mời.")}/>}</View>)}</View>}
<Text style={s.h2}>Hoạt động</Text>{activity.length?activity.map((a:any)=><Text key={a.id}>{a.actorSnapshotName??"Thành viên"} · {a.type}</Text>):<Text>Chưa có hoạt động.</Text>}
<View style={s.panel}><Text style={s.h2}>Chia sẻ vị trí</Text><Text style={s.strong}>OFF mặc định.</Text><Text>Ứng dụng chỉ xin quyền foreground sau khi bạn tự bật chia sẻ và bấm “Cập nhật vị trí từ thiết bị”. Không chạy nền, không tự thu thập.</Text><Text>Trạng thái: {sharing?.status??"OFF"} · {sharing?.locationAvailability??"UNAVAILABLE"}</Text>{sharing?.status==="ACTIVE"?<><Action label="Cập nhật vị trí từ thiết bị" onPress={pushLocation}/><Action label="Dừng chia sẻ ngay" onPress={()=>safe(()=>mobileApi.stopTripLocationSharing(id),"Đã dừng chia sẻ vị trí.")}/></>:<><TextInput accessibilityLabel="Thời lượng chia sẻ theo phút" value={duration} onChangeText={setDuration} keyboardType="number-pad" style={s.input}/><Action label="Tự nguyện bật chia sẻ" onPress={start}/></>}</View>
<Text style={s.h2}>Vị trí đang khả dụng</Text>{locations.length?locations.map((l:any,i)=><Text key={l.userId??i}>{l.displayName??l.userId??"Thành viên"} · {l.availability??"UNAVAILABLE"}{l.latitude!==undefined?" · "+Number(l.latitude).toFixed(4)+", "+Number(l.longitude).toFixed(4):""}</Text>):<Text>Không có vị trí khả dụng.</Text>}
<Text style={s.h2}>Chi phí thực tế</Text>{summary?.totalsByCurrency?.map((x:any)=><Text key={x.currency}>Tổng {x.totalAmount} {x.currency}</Text>)}{expenses.map((x:any)=><View key={x.id} style={s.card}><Text>{x.title} · {x.amount} {x.currency}</Text>{canEdit&&<Action label="Xóa" onPress={()=>safe(()=>mobileApi.deleteTripExpense(id,x.id,x.version),"Đã xóa chi phí.")}/>}</View>)}{canEdit&&<View style={s.panel}><TextInput accessibilityLabel="Nội dung chi phí" value={expenseTitle} onChangeText={setExpenseTitle} placeholder="Nội dung" style={s.input}/><TextInput accessibilityLabel="Số tiền" value={expenseAmount} onChangeText={setExpenseAmount} keyboardType="decimal-pad" placeholder="Số tiền VND" style={s.input}/><Action label="Ghi chi phí" onPress={addExpense}/></View>}
<Text style={s.h2}>Số dư & thanh toán</Text>{summary?.balancesByCurrency?.flatMap((g:any)=>g.balances??[]).map((b:any,i:number)=><Text key={(b.userId??"u")+i}>{b.displayName??b.userId}: {b.netAmount}</Text>)}{settlements.map((x:any)=><Text key={x.id}>{x.fromUserId} → {x.toUserId}: {x.amount} {x.currency}</Text>)}{suggestions.flatMap((g:any)=>g.suggestions??[]).length===0&&<Text>Không có khoản cần cân đối.</Text>}{suggestions.map((g:any)=>g.suggestions?.map((x:any,i:number)=><View key={g.currency+i} style={s.card}><Text>{x.fromDisplayName??x.fromUserId} → {x.toDisplayName??x.toUserId}: {x.amount} {g.currency}</Text>{canEdit&&<Action label="Ghi đã thanh toán" onPress={()=>safe(()=>mobileApi.createTripSettlement(id,{fromUserId:x.fromUserId,toUserId:x.toUserId,amount:String(x.amount),currency:g.currency,settledAt:new Date().toISOString().slice(0,10),note:"Ghi nhận thanh toán ngoài Dấu Việt"}),"Đã ghi nhận thanh toán.")}/>}</View>))}
{!!message&&<Text accessibilityLiveRegion="polite">{message}</Text>}</View></AppShell>}
function Action({label,onPress}:{label:string;onPress:()=>void|Promise<void>}){return <Pressable accessibilityRole="button" style={s.button} onPress={()=>void onPress()}><Text>{label}</Text></Pressable>}
const s=StyleSheet.create({body:{gap:12},title:{fontSize:30,fontWeight:"600",color:"#062A24"},h2:{fontSize:20,fontWeight:"600",color:"#18463C",marginTop:8},strong:{fontWeight:"700"},panel:{gap:10,padding:14,borderWidth:1,borderColor:"#D4AF7C",borderRadius:12},card:{gap:8,padding:12,borderWidth:1,borderColor:"#EADDC7",borderRadius:10},row:{gap:8,flexDirection:"row",flexWrap:"wrap"},input:{minHeight:48,borderWidth:1,borderColor:"#B6B6B6",borderRadius:10,paddingHorizontal:12},button:{minHeight:44,borderWidth:1,borderColor:"#18463C",borderRadius:10,alignItems:"center",justifyContent:"center",paddingHorizontal:12}});
