/**
 * Machine-readable editorial (Story/Journey) error codes (Phase 06). Same
 * pattern as `AUTH_ERROR_CODES`/`TRUST_ERROR_CODES`/`MEDIA_ERROR_CODES`.
 */
export const EDITORIAL_ERROR_CODES = {
  STORY_INVALID_TRANSITION: 'STORY_INVALID_TRANSITION',
  STORY_PUBLICATION_REQUIREMENTS_NOT_MET: 'STORY_PUBLICATION_REQUIREMENTS_NOT_MET',
  STORY_TRANSLATION_REQUIRED: 'STORY_TRANSLATION_REQUIRED',
  STORY_MEDIA_NOT_READY: 'STORY_MEDIA_NOT_READY',
  STORY_FACT_NOT_PUBLISHABLE: 'STORY_FACT_NOT_PUBLISHABLE',
  STORY_SOURCE_RESTRICTED: 'STORY_SOURCE_RESTRICTED',
  STORY_REVIEW_REQUIRED: 'STORY_REVIEW_REQUIRED',
  STORY_VERSION_CONFLICT: 'STORY_VERSION_CONFLICT',

  JOURNEY_INVALID_TRANSITION: 'JOURNEY_INVALID_TRANSITION',
  JOURNEY_STOP_REQUIRED: 'JOURNEY_STOP_REQUIRED',
  JOURNEY_DUPLICATE_STOP: 'JOURNEY_DUPLICATE_STOP',
  JOURNEY_INVALID_STOP_ORDER: 'JOURNEY_INVALID_STOP_ORDER',
  JOURNEY_MEDIA_NOT_READY: 'JOURNEY_MEDIA_NOT_READY',
  JOURNEY_VERSION_CONFLICT: 'JOURNEY_VERSION_CONFLICT',
} as const;
