"use client";
import {FormEvent,useEffect,useState} from "react";
import {useParams} from "next/navigation";
import {restoreWebSession,webApi} from "../../../auth/session";

type Member={id:string;userId:string;role:"EDITOR"|"VIEWER";user?:{id:string;displayName?:string}};
type Invitation={id:string;email:string;role:string;status:string;expiresAt:string};
type Activity={id:string;type:string;actorSnapshotName:string;createdAt:string};
type LocationStatus={status:string;startedAt?:string|null;expiresAt?:string|null;locationAvailability:string};
type Location={userId:string;displayName?:string;availability:string;latitude?:number;longitude?:number;accuracyMeters?:number;capturedAt?:string};
type Expense={id:string;title:string;category:string;amount:string;currency:string;payerUserId:string;splitMode:string;occurredOn:string};
type Summary={totalsByCurrency:Array<{currency:string;totalAmount:string}>;balancesByCurrency:Array<{currency:string;balances:Array<{userId:string;displayName?:string|null;netAmount:string}>}>};

export default function Together(){
 const {id}=useParams<{id:string}>(),[userId,setUserId]=useState(""),[ownerId,setOwnerId]=useState(""),[version,setVersion]=useState(0),[members,setMembers]=useState<Member[]>([]),[invites,setInvites]=useState<Invitation[]>([]),[activity,setActivity]=useState<Activity[]>([]),[sharing,setSharing]=useState<LocationStatus>(),[locations,setLocations]=useState<Location[]>([]),[expenses,setExpenses]=useState<Expense[]>([]),[summary,setSummary]=useState<Summary>(),[status,setStatus]=useState("Đang tải TOGETHER…");
 const role=ownerId===userId?"OWNER":members.find(m=>m.userId===userId||m.user?.id===userId)?.role,canEdit=role==="OWNER"||role==="EDITOR",canManage=role==="OWNER";
 async function load(){const me=await restoreWebSession();if(!me){location.assign("/auth/login");return}setUserId(me.id);try{const trip=await webApi.trip<{ownerId:string;version:number}>(id);setOwnerId(trip.ownerId);setVersion(trip.version);const [m,a,s,l,e,sum]=await Promise.all([webApi.tripMembers<Member[]>(id),webApi.tripActivity<{items:Activity[]}>(id),webApi.myTripLocationSharing<LocationStatus>(id),webApi.tripLocations<Location[]>(id),webApi.tripExpenses<{items:Expense[]}>(id),webApi.tripExpenseSummary<Summary>(id)]);setMembers(m);setActivity(a.items);setSharing(s);setLocations(l);setExpenses(e.items);setSummary(sum);if(trip.ownerId===me.id)setInvites(await webApi.tripInvitations<Invitation[]>(id));setStatus("")}catch{setStatus("Không thể tải không gian TOGETHER hoặc bạn không còn quyền truy cập.")}}
 useEffect(()=>{void load()},[id]);
 async function startSharing(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);try{setSharing(await webApi.startTripLocationSharing<LocationStatus>(id,Number(f.get("duration"))));setStatus("Đã bật chia sẻ vị trí cho chính bạn. Hệ thống chưa gửi tọa độ cho đến khi thiết bị chủ động cập nhật.")}catch{setStatus("Không thể bật chia sẻ vị trí. Kiểm tra thời lượng hoặc trạng thái hiện tại.")}}
 async function stopSharing(){try{setSharing(await webApi.stopTripLocationSharing<LocationStatus>(id));setStatus("Đã dừng chia sẻ vị trí.");await load()}catch{setStatus("Không thể dừng chia sẻ vị trí.")}}
 async function expense(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),amount=String(f.get("amount")),currency=String(f.get("currency")).toUpperCase(),payer=String(f.get("payer"));try{await webApi.createTripExpense(id,{title:String(f.get("title")),category:String(f.get("category")),amount,currency,payerUserId:payer,splitMode:"EQUAL",occurredOn:String(f.get("date")),shares:[{userId:payer}]});setStatus("Đã ghi chi phí thực tế.");await load()}catch{setStatus("Không thể ghi chi phí. Người trả phải là thành viên hiện tại và dữ liệu phải hợp lệ.")}}
 return <main id="main" className="auth-shell"><section className="auth-card"><a href={"/trips/"+id}>← Kế hoạch chuyến đi</a><p className="eyebrow">TOGETHER</p><h1>Đi cùng nhau</h1><p>Vai trò hiện tại: {role??"đang xác định"}</p>{status&&<p role="status">{status}</p>}
 <h2>Thành viên</h2>{members.length?members.map(m=><article key={m.id}><p>{m.user?.displayName??m.userId} · {m.role}</p>{canManage&&<div><button className="button button-quiet" onClick={async()=>{await webApi.updateTripMemberRole(id,m.id,m.role==="EDITOR"?"VIEWER":"EDITOR",version);await load()}}>Đổi thành {m.role==="EDITOR"?"VIEWER":"EDITOR"}</button><button className="button button-quiet" onClick={async()=>{await webApi.removeTripMember(id,m.id,version);await load()}}>Xóa thành viên</button></div>}</article>):<p>Chưa có thành viên khác.</p>}
 {canManage&&<><h3>Lời mời</h3>{invites.length?invites.map(x=><p key={x.id}>{x.email} · {x.role} · {x.status} {x.status==="PENDING"&&<button onClick={async()=>{await webApi.revokeTripInvitation(id,x.id);await load()}}>Thu hồi</button>}</p>):<p>Không có lời mời.</p>}</>}
 <h2>Hoạt động</h2>{activity.length?activity.map(a=><p key={a.id}>{a.actorSnapshotName} · {a.type} · {new Date(a.createdAt).toLocaleString("vi-VN")}</p>):<p>Chưa có hoạt động.</p>}
 <h2>Chia sẻ vị trí</h2><p>Vị trí luôn tắt mặc định và chỉ chính bạn có thể bật. Trạng thái: {sharing?.status??"—"} · dữ liệu: {sharing?.locationAvailability??"UNAVAILABLE"}</p>{sharing?.status==="ACTIVE"?<button className="button button-quiet" onClick={stopSharing}>Dừng chia sẻ ngay</button>:<form className="auth-form" onSubmit={startSharing}><label>Thời lượng (phút)<input name="duration" type="number" min={1} required defaultValue={60}/></label><button className="button button-quiet">Tự nguyện bật chia sẻ</button></form>}
 <h3>Vị trí thành viên đang khả dụng</h3>{locations.map(l=><p key={l.userId}>{l.displayName??l.userId} · {l.availability}{l.latitude!==undefined&&l.longitude!==undefined?" · "+l.latitude.toFixed(4)+", "+l.longitude.toFixed(4):""}</p>)}
 <h2>Chi phí thực tế</h2>{summary?.totalsByCurrency.map(t=><p key={t.currency}>Tổng {t.totalAmount} {t.currency}</p>)}{expenses.map(x=><p key={x.id}>{x.title} · {x.amount} {x.currency} · {x.category}</p>)}
 {canEdit&&<form className="auth-form" onSubmit={expense}><label>Nội dung<input name="title" required maxLength={200}/></label><label>Loại<select name="category"><option>STAY</option><option>FOOD</option><option>ACTIVITY</option><option>TRANSPORT</option><option>OTHER</option></select></label><label>Số tiền<input name="amount" inputMode="decimal" required/></label><label>Tiền tệ<input name="currency" defaultValue="VND" pattern="[A-Za-z]{3}" required/></label><label>Người trả<select name="payer" required><option value={ownerId}>Chủ chuyến đi</option>{members.map(m=><option key={m.id} value={m.userId}>{m.user?.displayName??m.userId}</option>)}</select></label><label>Ngày chi<input name="date" type="date" required/></label><button className="button button-gold">Ghi chi phí</button></form>}
 <h3>Số dư</h3>{summary?.balancesByCurrency.flatMap(g=>g.balances.map(b=><p key={g.currency+b.userId}>{b.displayName??b.userId}: {b.netAmount} {g.currency} {Number(b.netAmount)>0?"· được nhận":Number(b.netAmount)<0?"· cần trả":"· cân bằng"}</p>))}
 </section></main>
}