"use client";
import {FormEvent,useEffect,useState} from "react";
import {useParams} from "next/navigation";
import {restoreWebSession,webApi} from "../../../auth/session";
type Member={id:string;userId:string;role:"EDITOR"|"VIEWER";user?:{id:string;displayName?:string}};
type Invitation={id:string;email:string;role:string;status:string;expiresAt:string};
type Activity={id:string;type:string;actorSnapshotName:string;createdAt:string};
type Sharing={status:string;expiresAt?:string|null;locationAvailability:string};
type Loc={userId:string;displayName?:string;availability:string;latitude?:number;longitude?:number;accuracyMeters?:number;capturedAt?:string};
type Expense={id:string;version:number;title:string;category:string;amount:string;currency:string;payerUserId:string;splitMode:"EQUAL"|"EXACT"|"PERCENTAGE";occurredOn:string;shares?:Array<{userId:string;amount:string;percentage?:string|null}>};
type Summary={totalsByCurrency:Array<{currency:string;totalAmount:string}>;balancesByCurrency:Array<{currency:string;balances:Array<{userId:string;displayName?:string|null;netAmount:string}>}>};
type Settlement={id:string;fromUserId:string;toUserId:string;amount:string;currency:string;settledAt:string;createdAt:string};
type Suggest={currency:string;suggestions:Array<{fromUserId:string;toUserId:string;amount:string;fromDisplayName?:string|null;toDisplayName?:string|null}>};
export default function Together(){
 const {id}=useParams<{id:string}>(),[uid,setUid]=useState(""),[owner,setOwner]=useState(""),[version,setVersion]=useState(0),[members,setMembers]=useState<Member[]>([]),[invites,setInvites]=useState<Invitation[]>([]),[activity,setActivity]=useState<Activity[]>([]),[sharing,setSharing]=useState<Sharing>(),[locations,setLocations]=useState<Loc[]>([]),[expenses,setExpenses]=useState<Expense[]>([]),[summary,setSummary]=useState<Summary>(),[suggestions,setSuggestions]=useState<Suggest[]>([]),[settlements,setSettlements]=useState<Settlement[]>([]),[split,setSplit]=useState<"EQUAL"|"EXACT"|"PERCENTAGE">("EQUAL"),[status,setStatus]=useState("Đang tải TOGETHER…");
 const role=owner===uid?"OWNER":members.find(m=>m.userId===uid||m.user?.id===uid)?.role,canEdit=role==="OWNER"||role==="EDITOR",canManage=role==="OWNER",participants=[{userId:owner,name:"Chủ chuyến đi"},...members.map(m=>({userId:m.userId,name:m.user?.displayName??m.userId}))].filter(p=>p.userId);
 async function load(){const me=await restoreWebSession();if(!me){location.assign("/auth/login");return}setUid(me.id);try{const trip=await webApi.trip<{ownerId:string;version:number}>(id);setOwner(trip.ownerId);setVersion(trip.version);const [m,a,s,l,e,sum,sug,sett]=await Promise.all([webApi.tripMembers<Member[]>(id),webApi.tripActivity<{items:Activity[]}>(id),webApi.myTripLocationSharing<Sharing>(id),webApi.tripLocations<Loc[]>(id),webApi.tripExpenses<{items:Expense[]}>(id),webApi.tripExpenseSummary<Summary>(id),webApi.tripSettlementSuggestions<{suggestionsByCurrency:Suggest[]}>(id),webApi.tripSettlements<{items:Settlement[]}>(id)]);setMembers(m);setActivity(a.items);setSharing(s);setLocations(l);setExpenses(e.items);setSummary(sum);setSuggestions(sug.suggestionsByCurrency);setSettlements(sett.items);setInvites(trip.ownerId===me.id?await webApi.tripInvitations<Invitation[]>(id):[]);setStatus("")}catch{setStatus("Không thể tải TOGETHER hoặc bạn không còn quyền truy cập.")}}
 useEffect(()=>{void load()},[id]);
 async function safe(fn:()=>Promise<unknown>,ok:string,reload=true){try{await fn();setStatus(ok);if(reload)await load()}catch(e:any){setStatus(e?.code==="TRIP_VERSION_CONFLICT"?"Chuyến đi vừa thay đổi. Dữ liệu đã được tải lại; hãy kiểm tra rồi thử lại.":"Thao tác không thành công. Kiểm tra quyền, dữ liệu và trạng thái hiện tại.");await load()}}
 async function invite(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);await safe(()=>webApi.inviteTripMember(id,String(f.get("email")),String(f.get("role")) as "EDITOR"|"VIEWER"),"Đã gửi lời mời.")}
 async function start(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);try{const next=await webApi.startTripLocationSharing<Sharing>(id,Number(f.get("duration")));setSharing(next);setStatus("Đã bật chia sẻ cho chính bạn. Chưa có tọa độ nào được gửi cho tới khi bạn bấm Cập nhật vị trí.")}catch{setStatus("Không thể bật chia sẻ vị trí. Kiểm tra thời lượng hoặc trạng thái hiện tại.")}}
 function pushLocation(){if(!navigator.geolocation){setStatus("Trình duyệt không hỗ trợ vị trí.");return}setStatus("Đang xin quyền vị trí từ thiết bị…");navigator.geolocation.getCurrentPosition(p=>void safe(()=>webApi.updateTripLocation(id,{latitude:p.coords.latitude,longitude:p.coords.longitude,accuracyMeters:p.coords.accuracy,capturedAt:new Date(p.timestamp).toISOString()}),"Đã cập nhật vị trí hiện tại."),()=>setStatus("Không có quyền vị trí hoặc thiết bị không thể xác định vị trí."),{enableHighAccuracy:true,maximumAge:0,timeout:15000})}
 async function addExpense(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),amount=String(f.get("amount")),currency=String(f.get("currency")).toUpperCase();const shares=participants.filter(p=>f.get("share-"+p.userId)!==null).map(p=>{const raw=String(f.get("share-"+p.userId)||"");return split==="EQUAL"?{userId:p.userId}:split==="EXACT"?{userId:p.userId,amount:raw}:{userId:p.userId,percentage:raw}});await safe(()=>webApi.createTripExpense(id,{title:String(f.get("title")),category:String(f.get("category")),amount,currency,payerUserId:String(f.get("payer")),splitMode:split,occurredOn:String(f.get("date")),shares}),"Đã ghi chi phí thực tế.")}
 async function editExpense(x:Expense){const title=window.prompt("Nội dung chi phí",x.title);if(title===null)return;const amount=window.prompt("Số tiền",String(x.amount));if(amount===null)return;const shares=(x.shares??[]).map(s=>x.splitMode==="EQUAL"?{userId:s.userId}:x.splitMode==="EXACT"?{userId:s.userId,amount:String(s.amount)}:{userId:s.userId,percentage:String(s.percentage)});await safe(()=>webApi.updateTripExpense(id,x.id,{title,category:x.category,amount,currency:x.currency,payerUserId:x.payerUserId,splitMode:x.splitMode,occurredOn:String(x.occurredOn).slice(0,10),shares,expectedVersion:x.version}),"Đã cập nhật chi phí.")}
 async function settle(s:Suggest["suggestions"][number],currency:string){await safe(()=>webApi.createTripSettlement(id,{fromUserId:s.fromUserId,toUserId:s.toUserId,amount:String(s.amount),currency,settledAt:new Date().toISOString().slice(0,10),note:"Ghi nhận thanh toán ngoài Dấu Việt"}),"Đã ghi nhận thanh toán ngoài Dấu Việt.")}
 return <main id="main" className="auth-shell"><section className="auth-card"><a href={"/trips/"+id}>← Kế hoạch</a><p className="eyebrow">TOGETHER</p><h1>Đi cùng nhau</h1><p>Vai trò: {role??"—"}</p>{status&&<p role="status">{status}</p>}
 <h2>Thành viên</h2>{members.length?members.map(m=><article key={m.id}><p>{m.user?.displayName??m.userId} · {m.role}</p>{canManage&&<><button className="button button-quiet" onClick={()=>void safe(()=>webApi.updateTripMemberRole(id,m.id,m.role==="EDITOR"?"VIEWER":"EDITOR",version),"Đã đổi vai trò.")}>Đổi thành {m.role==="EDITOR"?"VIEWER":"EDITOR"}</button><button className="button button-quiet" onClick={()=>void safe(()=>webApi.removeTripMember(id,m.id,version),"Đã xóa thành viên.")}>Xóa</button><button className="button button-quiet" onClick={()=>{if(confirm("Chuyển quyền sở hữu cho thành viên này? Bạn sẽ trở thành EDITOR."))void safe(()=>webApi.transferTripOwnership(id,m.userId,version),"Đã chuyển quyền sở hữu.")}}>Chuyển quyền sở hữu</button></>}</article>):<p>Chưa có thành viên khác.</p>}{role!=="OWNER"&&role&&<button className="button button-quiet" onClick={()=>{if(confirm("Rời chuyến đi? Chia sẻ vị trí của bạn cũng sẽ bị dừng."))void safe(()=>webApi.leaveTrip(id,version),"Đã rời chuyến đi.")}}>Rời chuyến đi</button>}
 {canManage&&<><h3>Lời mời</h3><form className="auth-form" onSubmit={invite}><label>Email<input name="email" type="email" required/></label><label>Vai trò<select name="role"><option value="VIEWER">VIEWER</option><option value="EDITOR">EDITOR</option></select></label><button className="button button-gold">Mời cộng tác</button></form>{invites.length?invites.map(x=><p key={x.id}>{x.email} · {x.role} · {x.status} {x.status==="PENDING"&&<button onClick={()=>void safe(()=>webApi.revokeTripInvitation(id,x.id),"Đã thu hồi lời mời.")}>Thu hồi</button>}</p>):<p>Không có lời mời.</p>}</>}
 <h2>Hoạt động</h2>{activity.length?activity.map(a=><p key={a.id}>{a.actorSnapshotName} · {a.type} · {new Date(a.createdAt).toLocaleString("vi-VN")}</p>):<p>Chưa có hoạt động.</p>}
 <h2>Chia sẻ vị trí</h2><p>OFF mặc định; chỉ bạn có thể bật cho chính mình. {sharing?.status??"—"} · {sharing?.locationAvailability??"UNAVAILABLE"}</p>{sharing?.status==="ACTIVE"?<><button className="button button-gold" onClick={pushLocation}>Cập nhật vị trí từ thiết bị</button><button className="button button-quiet" onClick={()=>void safe(()=>webApi.stopTripLocationSharing(id),"Đã dừng chia sẻ vị trí.")}>Dừng chia sẻ ngay</button></>:<form className="auth-form" onSubmit={start}><label>Thời lượng (phút)<input name="duration" type="number" min={1} defaultValue={60} required/></label><button className="button button-quiet">Tự nguyện bật chia sẻ</button></form>}
 <h3>Vị trí đang khả dụng</h3>{locations.length?locations.map(l=><p key={l.userId}>{l.displayName??l.userId} · {l.availability}{l.latitude!==undefined?" · "+l.latitude.toFixed(4)+", "+l.longitude!.toFixed(4):""}</p>):<p>Không có vị trí khả dụng.</p>}
 <h2>Chi phí thực tế</h2>{summary?.totalsByCurrency.map(t=><p key={t.currency}>Tổng {String(t.totalAmount)} {t.currency}</p>)}{expenses.length?expenses.map(x=><p key={x.id}>{x.title} · {String(x.amount)} {x.currency} · {x.category}{canEdit&&<><button onClick={()=>void editExpense(x)}>Sửa</button><button onClick={()=>void safe(()=>webApi.deleteTripExpense(id,x.id,x.version),"Đã xóa chi phí.")}>Xóa</button></>}</p>):<p>Chưa có chi phí thực tế.</p>}
 {canEdit&&<form className="auth-form" onSubmit={addExpense}><label>Nội dung<input name="title" required maxLength={200}/></label><label>Loại<select name="category"><option>STAY</option><option>FOOD</option><option>ACTIVITY</option><option>TRANSPORT</option><option>OTHER</option></select></label><label>Số tiền<input name="amount" inputMode="decimal" required/></label><label>Tiền tệ<input name="currency" defaultValue="VND" pattern="[A-Za-z]{3}" required/></label><label>Người trả<select name="payer">{participants.map(p=><option key={p.userId} value={p.userId}>{p.name}</option>)}</select></label><label>Ngày chi<input name="date" type="date" required/></label><label>Chia<select value={split} onChange={e=>setSplit(e.target.value as any)}><option>EQUAL</option><option>EXACT</option><option>PERCENTAGE</option></select></label>{participants.map(p=><label key={p.userId}>{p.name}{split==="EQUAL"?<input type="checkbox" name={"share-"+p.userId} value="1" defaultChecked/>:<input name={"share-"+p.userId} placeholder={split==="EXACT"?"Số tiền":"Phần trăm"} required/>}</label>)}<button className="button button-gold">Ghi chi phí</button></form>}
 <h3>Số dư</h3>{summary?.balancesByCurrency.flatMap(g=>g.balances.map(b=><p key={g.currency+b.userId}>{b.displayName??b.userId}: {String(b.netAmount)} {g.currency} {Number(b.netAmount)>0?"· được nhận":Number(b.netAmount)<0?"· cần trả":"· cân bằng"}</p>))}
 <h3>Lịch sử thanh toán ngoài Dấu Việt</h3>{settlements.length?settlements.map(s=><p key={s.id}>{s.fromUserId} → {s.toUserId}: {String(s.amount)} {s.currency} · {String(s.settledAt).slice(0,10)}</p>):<p>Chưa ghi nhận thanh toán.</p>}
 <h3>Gợi ý thanh toán</h3>{suggestions.flatMap(g=>g.suggestions).length?suggestions.flatMap(g=>g.suggestions.map((s,i)=><p key={g.currency+i}>{s.fromDisplayName??s.fromUserId} → {s.toDisplayName??s.toUserId}: {String(s.amount)} {g.currency}{canEdit&&<button onClick={()=>void settle(s,g.currency)}>Ghi đã thanh toán</button>}</p>)):<p>Không có khoản cần cân đối.</p>}
 </section></main>
}