"use client";
import {FormEvent,useEffect,useState} from "react";
import {useParams} from "next/navigation";
import {webApi} from "../../../auth/session";
type Detail={slug:string;translation?:{name?:string;summary?:string}};
type Offer={providerCode:string;currency:string;amount:string;totalAmount?:string|null;availability:string;fetchedAt:string;attribution?:{displayText?:string|null}};
export default function Stay(){const {slug}=useParams<{slug:string}>();const [d,setD]=useState<Detail>();const [offers,setOffers]=useState<Offer[]>([]);const [status,setStatus]=useState("Đang tải nơi ở…");const [busy,setBusy]=useState(false);
useEffect(()=>{webApi.accommodation<Detail>(slug).then(x=>{setD(x);setStatus("")}).catch(()=>setStatus("Không thể tải nơi ở này."))},[slug]);
async function search(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setOffers([]);setStatus("Đang kiểm tra dữ liệu nhà cung cấp hiện tại…");const f=new FormData(e.currentTarget);try{const r=await webApi.accommodationOffers<{offers:Offer[]}>(slug,{checkIn:String(f.get("checkIn")),checkOut:String(f.get("checkOut")),guests:Number(f.get("guests")),rooms:Number(f.get("rooms")),currency:String(f.get("currency")).toUpperCase()});setOffers(r.offers);setStatus(r.offers.length?"":"Không có ưu đãi hiện tại đủ điều kiện. Dấu Việt không suy đoán giá hoặc khả năng còn chỗ.")}catch{setStatus("Không thể lấy dữ liệu nhà cung cấp. Không có giá hay khả năng đặt nào được dựng giả.")}finally{setBusy(false)}}
return <main id="main" className="auth-shell"><section className="auth-card"><div className="eyebrow">BOOK · STAY</div><h1>{d?.translation?.name??slug}</h1>{d?.translation?.summary&&<p>{d.translation.summary}</p>}<p>Dữ liệu giá và khả dụng chỉ xuất hiện sau khi bạn nhập ngữ cảnh chuyến đi và khi nhà cung cấp hiện đủ điều kiện.</p><form className="auth-form" onSubmit={search}><label>Nhận phòng<input name="checkIn" type="date" required/></label><label>Trả phòng<input name="checkOut" type="date" required/></label><label>Khách<input name="guests" type="number" min="1" defaultValue="2" required/></label><label>Phòng<input name="rooms" type="number" min="1" defaultValue="1" required/></label><label>Tiền tệ<input name="currency" pattern="[A-Za-z]{3}" defaultValue="VND" required/></label><button className="button button-gold" disabled={busy}>{busy?"Đang kiểm tra…":"Kiểm tra ưu đãi"}</button></form><p role="status">{status}</p>{offers.map((o,i)=><article key={i}><h2>{o.providerCode}</h2><p>{o.totalAmount??o.amount} {o.currency} · {o.availability}</p>{o.attribution?.displayText&&<p>{o.attribution.displayText}</p>}<p>Dữ liệu nhà cung cấp · cập nhật {new Date(o.fetchedAt).toLocaleString()}</p></article>)}</section></main>}