"use client";
import{useEffect,useState}from"react";
type Stop={order:number;place:{id:string;slug:string;name?:string|null;location?:{latitude:number;longitude:number}|null};stopTitle?:string|null;recommendedDurationMinutes?:number|null;notes?:string|null;story?:{id:string;slug:string}|null;event?:{id:string;slug:string}|null};
type Journey={id:string;slug:string;durationMinutes?:number|null;distanceMeters?:number|null;difficulty?:string|null;region?:string|null;editorialStatus:string;publishedAt?:string|null;heroMedia?:{id:string;type:string;isAiGenerated:boolean;aiDisclosure?:string|null;accessPolicy:string;status:string}|null;routeGeometrySource?:string|null;stops:Stop[];translation?:{title?:string;summary?:string|null;description?:string|null}|null;meta:{requestedLocale:string;resolvedLocale:string;fallbackApplied:boolean}};
const API=(process.env.NEXT_PUBLIC_API_URL??"http://localhost:3000").replace(/\/$/,"");
const mins=(n:number)=>n>=60?`${Math.floor(n/60)} giờ${n%60?` ${n%60} phút`:""}`:`${n} phút`;
export default function JourneyDetail({slug}:{slug:string}){const[data,setData]=useState<Journey|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState("");useEffect(()=>{const c=new AbortController();fetch(`${API}/v1/journeys/${encodeURIComponent(slug)}?locale=vi`,{credentials:"include",signal:c.signal}).then(async r=>{const p=await r.json();if(!r.ok)throw new Error(p?.error?.message??"Không thể tải hành trình.");return p?.data??p}).then(setData).catch(e=>{if(!c.signal.aborted)setError(e instanceof Error?e.message:"Không thể tải hành trình.")}).finally(()=>{if(!c.signal.aborted)setLoading(false)});return()=>c.abort()},[slug]);
if(loading)return <main id="main" className="journey-state" aria-live="polite">Đang mở hành trình…</main>;if(error||!data)return <main id="main" className="journey-state"><div className="eyebrow">Journey</div><h1>Không thể mở hành trình</h1><p>{error||"Không tìm thấy hành trình đã xuất bản."}</p><a className="button button-gold" href="/explore">Quay lại khám phá</a></main>;
const t=data.translation??{};return <main id="main" className="journey-page"><header className="journey-hero"><div className="container journey-hero-inner"><div className="eyebrow">Curated Journey{data.region?` · ${data.region}`:""}</div><h1>{t.title??data.slug}</h1>{t.summary&&<p>{t.summary}</p>}<div className="journey-metrics">{data.durationMinutes!=null&&<span><strong>{mins(data.durationMinutes)}</strong>Thời lượng</span>}{data.distanceMeters!=null&&<span><strong>{data.distanceMeters>=1000?`${(data.distanceMeters/1000).toFixed(1)} km`:`${data.distanceMeters} m`}</strong>Khoảng cách</span>}{data.difficulty&&<span><strong>{data.difficulty}</strong>Mức độ</span>}<span><strong>{data.stops.length}</strong>Điểm dừng</span></div>{data.meta.fallbackApplied&&<p className="locale-fallback">Ngôn ngữ dự phòng: {data.meta.resolvedLocale}</p>}{data.heroMedia&&<div className="journey-media-disclosure"><strong>{data.heroMedia.type}</strong>{data.heroMedia.isAiGenerated&&<span>AI / Reconstruction{data.heroMedia.aiDisclosure?`: ${data.heroMedia.aiDisclosure}`:""}</span>}</div>}</div></header>
<section className="section"><div className="container journey-intro"><div><div className="eyebrow">Experience</div><h2>Đi qua câu chuyện theo từng địa điểm</h2></div><p>{t.description??"Chưa có mô tả hành trình đã xuất bản."}</p></div></section>
<section className="section journey-route"><div className="container"><div className="journey-section-head"><div><div className="eyebrow">Ordered Stops</div><h2>Lộ trình biên tập</h2></div><p>{data.routeGeometrySource?"Hình học tuyến đường có nguồn được công bố.":"Các điểm dừng được sắp theo thứ tự biên tập; không giả định tuyến đường giữa chúng."}</p></div>{data.stops.length?<ol className="journey-stops">{data.stops.map((s,i)=><li key={s.place.id}><div className="journey-stop-index">{String(i+1).padStart(2,"0")}</div><article><div className="eyebrow">{s.stopTitle??`Điểm dừng ${i+1}`}</div><h3><a href={`/places/${s.place.slug}`}>{s.place.name??s.place.slug}</a></h3>{s.notes&&<p>{s.notes}</p>}<div className="journey-stop-meta">{s.recommendedDurationMinutes!=null&&<span>Gợi ý: {mins(s.recommendedDurationMinutes)}</span>}{s.place.location&&<span>{s.place.location.latitude.toFixed(4)}, {s.place.location.longitude.toFixed(4)}</span>}</div><div className="journey-stop-links">{s.story&&<a href={`/stories/${s.story.slug}`}>Đọc câu chuyện liên quan</a>}{s.event&&<a href={`/events/${s.event.slug}`}>Xem sự kiện liên quan</a>}</div></article></li>)}</ol>:<p className="destination-empty">Chưa có điểm dừng đã xuất bản.</p>}</div></section>
<section className="section journey-trust"><div className="container"><div className="eyebrow">Route & Trust</div><h2>Những gì hành trình thực sự biết</h2><p>{data.routeGeometrySource?`Nguồn hình học tuyến: ${data.routeGeometrySource}`:"Backend không cung cấp hình học tuyến đường cho hành trình này. Giao diện chỉ thể hiện thứ tự các Place đã xuất bản, không nối thành tuyến đường giả định."}</p><p>Media hero chỉ được hiển thị dưới dạng metadata disclosure khi API không cung cấp URL công khai.</p></div></section></main>}
