import { expect, test, type Page } from "@playwright/test";

const stories={items:[{id:"s1",slug:"story-one",title:"Một câu chuyện đã xuất bản",type:"EDITORIAL"}],nextCursor:null,hasMore:false};
const journeys={items:[{id:"j1",slug:"journey-one",title:"Một hành trình đã xuất bản",type:"CURATED"}],nextCursor:null,hasMore:false};
const results={results:[{entityType:"EVENT",id:"e1",slug:"event-one",title:"Sự kiện đã xuất bản",summary:"Bối cảnh từ kho tri thức.",trustClass:"VERIFIED_KNOWLEDGE",actualLocale:"vi",fallbackUsed:false},{entityType:"TERRITORY",id:"t1",slug:"territory-one",title:"Lãnh thổ lịch sử",trustClass:"VERIFIED_KNOWLEDGE",actualLocale:"vi",fallbackUsed:false}]};
async function mock(page:Page, fail=false){await page.route("**/v1/**",route=>{const u=new URL(route.request().url());if(fail)return route.fulfill({status:503,json:{error:{message:"fixture failure"}}});if(u.pathname==="/v1/stories")return route.fulfill({json:{data:stories}});if(u.pathname==="/v1/journeys")return route.fulfill({json:{data:journeys}});if(u.pathname==="/v1/search")return route.fulfill({json:{data:results}});return route.fulfill({status:404,json:{}})})}
for(const width of [320,390,768,1024,1440]) test(`collections responsive ${width}`,async({page})=>{await mock(page);await page.setViewportSize({width,height:900});for(const path of ["/stories","/journeys"]){await page.goto(path);await expect(page.getByRole("heading",{level:1})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)}});
test("collections expose truthful loading/success navigation",async({page})=>{await mock(page);await page.goto("/stories");await expect(page.getByRole("link",{name:/Mở nội dung/})).toHaveAttribute("href","/stories/story-one?locale=vi");await page.goto("/journeys?locale=en");await expect(page.getByRole("heading",{level:1})).toContainText("Curated journeys");await expect(page.getByRole("link",{name:/Open/})).toHaveAttribute("href","/journeys/journey-one?locale=en")});
test("collection failure offers keyboard-accessible retry",async({page})=>{await mock(page,true);await page.goto("/stories");await expect(page.getByRole("alert").filter({hasText:"Chưa thể tải danh sách"})).toBeVisible();await expect(page.getByRole("button",{name:"Thử lại"})).toBeVisible();await page.getByRole("button",{name:"Thử lại"}).focus();await expect(page.getByRole("button",{name:"Thử lại"})).toBeFocused()});
test("explore search keeps unsupported territory on map and canonical event route",async({page})=>{await mock(page);await page.goto("/explore");const input=page.getByLabel("Tìm kiếm");await input.fill("lịch sử");await page.getByRole("button",{name:"Tìm kiếm"}).click();await expect(page.getByRole("link",{name:/Mở nội dung/})).toHaveAttribute("href","/events/event-one?locale=vi");await expect(page.getByRole("link",{name:/Xem trên bản đồ/})).toHaveAttribute("href","/map");expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)});
test("explore error, EN locale, focus and reduced motion",async({page})=>{await mock(page,true);await page.emulateMedia({reducedMotion:"reduce"});await page.setViewportSize({width:320,height:800});await page.goto("/explore?locale=en");await expect(page.getByRole("heading",{level:1})).toContainText("Explore places");await page.getByRole("textbox",{name:"Search",exact:true}).fill("history");await page.getByRole("button",{name:"Search"}).click();await expect(page.getByRole("button",{name:"Retry"})).toBeVisible();await page.getByRole("button",{name:"Retry"}).focus();await expect(page.getByRole("button",{name:"Retry"})).toBeFocused();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)});
