import {expect,test,type Page,type Route} from "@playwright/test";
const json=(r:Route,data:unknown)=>r.fulfill({status:200,contentType:"application/json",body:JSON.stringify({success:true,data})});
async function setup(page:Page,role:"OWNER"|"EDITOR"|"VIEWER"="OWNER",onInvitationPost?:(body:any)=>void){
 await page.route("**/v1/auth/refresh",r=>json(r,{accessToken:"token",expiresIn:900}));await page.route("**/v1/users/me",r=>json(r,{id:"user-1",email:"me@example.com"}));
 const owner=role==="OWNER"?"user-1":"owner-1";await page.route("**/v1/trips/trip-1",r=>json(r,{id:"trip-1",ownerId:owner,version:4}));
 const members=role==="OWNER"?[{id:"m2",userId:"user-2",role:"EDITOR",user:{id:"user-2",displayName:"Lan"}}]:[{id:"m1",userId:"user-1",role,user:{id:"user-1",displayName:"Tôi"}}];
 await page.route("**/v1/trips/trip-1/members",r=>json(r,members));await page.route("**/v1/trips/trip-1/activity**",r=>json(r,{items:[],total:0,page:1,pageSize:20}));
 await page.route("**/v1/trips/trip-1/location-sharing/me",r=>json(r,{status:"NEVER_SHARED",locationAvailability:"UNAVAILABLE"}));await page.route("**/v1/trips/trip-1/locations",r=>json(r,[]));
 await page.route(/\/v1\/trips\/trip-1\/expenses(?:\?.*)?$/,r=>json(r,{items:[],total:0,page:1,pageSize:20}));await page.route("**/v1/trips/trip-1/expenses/summary",r=>json(r,{totalsByCurrency:[],balancesByCurrency:[]}));
 await page.route("**/v1/trips/trip-1/settlement-suggestions",r=>json(r,{suggestionsByCurrency:[]}));await page.route(/\/v1\/trips\/trip-1\/settlements(?:\?.*)?$/,r=>json(r,{items:[],total:0,page:1,pageSize:20}));await page.route("**/v1/trips/trip-1/invitations",r=>{if(r.request().method()==="POST"){const body=r.request().postDataJSON();onInvitationPost?.(body);return json(r,{id:"i1",email:body.email,role:body.role,status:"PENDING"})}return json(r,[])});
}
test("owner together workspace exposes governance finance and explicit location consent",async({page})=>{await setup(page);await page.goto("/trips/trip-1/together");await expect(page.getByRole("heading",{name:"Đi cùng nhau"})).toBeVisible();await expect(page.getByRole("button",{name:"Chuyển quyền sở hữu"})).toBeVisible();await expect(page.getByRole("button",{name:"Tự nguyện bật chia sẻ"})).toBeVisible();await expect(page.getByRole("button",{name:"Ghi chi phí"})).toBeVisible();await expect(page.getByText("OFF mặc định")).toBeVisible()});
test("viewer is read-only for governance and finance but controls own location consent",async({page})=>{await setup(page,"VIEWER");await page.goto("/trips/trip-1/together");await expect(page.getByText("Vai trò: VIEWER")).toBeVisible();await expect(page.getByRole("button",{name:"Chuyển quyền sở hữu"})).toHaveCount(0);await expect(page.getByRole("button",{name:"Ghi chi phí"})).toHaveCount(0);await expect(page.getByRole("button",{name:"Tự nguyện bật chia sẻ"})).toBeVisible();await expect(page.getByRole("button",{name:"Rời chuyến đi"})).toBeVisible()});
test("location consent start is explicit and does not send coordinates",async({page})=>{await setup(page);let body:any;await page.route("**/v1/trips/trip-1/location-sharing/start",async r=>{body=r.request().postDataJSON();await json(r,{status:"ACTIVE",expiresAt:"2026-10-01T00:00:00Z",locationAvailability:"UNAVAILABLE"})});await page.goto("/trips/trip-1/together");await page.getByRole("button",{name:"Tự nguyện bật chia sẻ"}).click();await expect.poll(()=>body?.durationMinutes).toBe(60);expect(body.latitude).toBeUndefined();await expect(page.getByRole("button",{name:"Cập nhật vị trí từ thiết bị"})).toBeVisible()});

test("editor can manage finance but cannot manage members or invitations",async({page})=>{await setup(page,"EDITOR");await page.goto("/trips/trip-1/together");await expect(page.getByText("Vai trò: EDITOR")).toBeVisible();await expect(page.getByRole("button",{name:"Ghi chi phí"})).toBeVisible();await expect(page.getByRole("button",{name:"Mời cộng tác"})).toHaveCount(0);await expect(page.getByRole("button",{name:"Chuyển quyền sở hữu"})).toHaveCount(0)});
test("owner can create invitation from together workspace",async({page})=>{let resolvePost!:(body:any)=>void;const invitationPost=new Promise<any>(resolve=>{resolvePost=resolve});await setup(page,"OWNER",resolvePost);await page.goto("/trips/trip-1/together");await page.getByLabel("Email").fill("lan@example.com");const [,body]=await Promise.all([page.getByRole("button",{name:"Mời cộng tác"}).click(),invitationPost]);expect(body).toMatchObject({email:"lan@example.com",role:"VIEWER"})});
