"use client";
import {FormEvent,useMemo,useState} from "react";
type Result={entityType:string;id:string;slug:string;title:string;summary?:string|null;trustClass:string;actualLocale?:string|null;fallbackUsed?:boolean};
const API=(process.env.NEXT_PUBLIC_API_URL??"http://localhost:3000").replace(/\/$/,"");
const routes:Record<string,string>={COUNTRY:"countries",REGION:"regions",DESTINATION:"destinations",PLACE:"places",STORY:"stories",JOURNEY:"journeys",PERSON:"people",EVENT:"events"};
const labels:Record<string,{vi:string;en:string}>={COUNTRY:{vi:"Quốc gia",en:"Country"},REGION:{vi:"Vùng",en:"Region"},DESTINATION:{vi:"Điểm đến",en:"Destination"},PLACE:{vi:"Địa điểm",en:"Place"},STORY:{vi:"Câu chuyện",en:"Story"},JOURNEY:{vi:"Hành trình",en:"Journey"},PERSON:{vi:"Nhân vật",en:"Person"},EVENT:{vi:"Sự kiện",en:"Event"}};
export default function ExploreSearch({locale}:{locale:"vi"|"en"}){
 const en=locale==="en";const[q,setQ]=useState(""),[results,setResults]=useState<Result[]>([]),[loading,setLoading]=useState(false),[error,setError]=useState(false),[searched,setSearched]=useState(false),[type,setType]=useState("ALL");
 const visible=useMemo(()=>type==="ALL"?results:results.filter(r=>r.entityType===type),[results,type]);
 async function runSearch(){const value=q.trim();if(!value)return;setLoading(true);setError(false);setSearched(true);try{const r=await fetch(`${API}/v1/search?q=${encodeURIComponent(value)}&locale=${locale}&limit=20`);if(!r.ok)throw new Error();const p=await r.json();setResults((p?.data??p)?.results??[])}catch{setError(true);setResults([])}finally{setLoading(false)}}
 function submit(e:FormEvent){e.preventDefault();void runSearch()}
 return <section className="discovery-search" aria-labelledby="explore-search-title">
  <div className="discovery-search-head"><div><p className="collection-kicker">{en?"Search":"Tìm kiếm"}</p><h2 id="explore-search-title">{en?"Find a place, then follow its story":"Tìm một nơi, rồi đi theo câu chuyện của nó"}</h2><p>{en?"Search only published knowledge. Continue to the map when spatial context matters.":"Chỉ tìm trong tri thức đã xuất bản. Chuyển sang bản đồ khi bạn muốn hiểu vị trí và các dấu vết xung quanh."}</p></div><a className="discovery-map-cta" href="/map">{en?"Explore on map":"Khám phá trên bản đồ"} <span aria-hidden="true">→</span></a></div>
  <form className="collection-search" onSubmit={submit}><label className="sr-only" htmlFor="global-discovery">{en?"Search":"Tìm kiếm"}</label><input id="global-discovery" value={q} onChange={e=>setQ(e.target.value)} placeholder={en?"Place, person, event, story…":"Địa điểm, nhân vật, sự kiện, câu chuyện…"} maxLength={200}/><button disabled={loading||!q.trim()}>{loading?(en?"Searching…":"Đang tìm…"):(en?"Search":"Tìm kiếm")}</button></form>
  {searched&&!error&&results.length>0&&<div className="discovery-result-toolbar"><strong>{en?`${results.length} published results`:`${results.length} kết quả đã xuất bản`}</strong><label>{en?"Filter":"Lọc"}<select value={type} onChange={e=>setType(e.target.value)}><option value="ALL">{en?"All types":"Tất cả"}</option>{Object.keys(labels).filter(k=>results.some(r=>r.entityType===k)).map(k=><option value={k} key={k}>{labels[k][locale]}</option>)}</select></label></div>}
  {error&&<div className="collection-state" role="alert"><strong>{en?"Search could not load":"Chưa thể tải tìm kiếm"}</strong><p>{en?"Your query was not lost. Try again when the connection is available.":"Truy vấn vẫn được giữ lại. Hãy thử lại khi kết nối ổn định."}</p><button type="button" onClick={()=>void runSearch()}>{en?"Retry":"Thử lại"}</button></div>}
  {!error&&searched&&!loading&&!results.length&&<div className="collection-state"><strong>{en?"No published match":"Chưa có kết quả đã xuất bản"}</strong><p>{en?"Try another name or use the map to browse spatially.":"Thử tên khác hoặc mở bản đồ để khám phá theo không gian."}</p><a href="/map">{en?"Open map":"Mở bản đồ"}</a></div>}
  {!error&&searched&&results.length>0&&!visible.length&&<p className="collection-state">{en?"No result in this filter.":"Không có kết quả thuộc bộ lọc này."}</p>}
  <div className="collection-grid">{visible.map(r=>{const base=routes[r.entityType];const href=base?`/${base}/${encodeURIComponent(r.slug)}?locale=${locale}`:"/map";return <article className="collection-card discovery-result-card" key={`${r.entityType}-${r.id}`}><div className="result-meta"><span>{labels[r.entityType]?.[locale]??r.entityType.replaceAll("_"," ")}</span>{r.trustClass&&<span>{r.trustClass}</span>}</div><h2>{r.title}</h2>{r.summary&&<p>{r.summary}</p>}{r.fallbackUsed&&<small>{en?`Content shown in ${r.actualLocale??"another language"}`:`Nội dung đang hiển thị bằng ${r.actualLocale??"ngôn ngữ dự phòng"}`}</small>}<a href={href}>{base?(en?"Open profile":"Mở hồ sơ"):(en?"View on map":"Xem trên bản đồ")} <span aria-hidden="true">↗</span></a></article>})}</div>
 </section>
}