export const eventCopy = {
  vi: {
    event: "Sự kiện", home: "Trang chủ", language: "Ngôn ngữ giao diện", map: "Khám phá bản đồ", breadcrumb: "Điều hướng sự kiện",
    loading: "Đang mở hồ sơ sự kiện…", missing: "Không tìm thấy sự kiện", error: "Chưa thể mở hồ sơ sự kiện", errorBody: "Hồ sơ hiện chưa khả dụng. Bạn có thể thử lại hoặc tiếp tục khám phá.", retry: "Thử lại",
    untitled: "Chưa có tiêu đề được cung cấp. Đang hiển thị mã định danh của hồ sơ.", noSummary: "Chưa có tóm tắt cho sự kiện này.", noDescription: "Nội dung diễn giải chi tiết chưa được cung cấp.",
    date: "Thời gian lịch sử", unknownDate: "Thời gian chưa được cung cấp", dateNote: "Thời gian được giữ nguyên theo hồ sơ, kể cả khoảng thời gian và mức độ chính xác.",
    fallback: "Ngôn ngữ dự phòng", requested: "Ngôn ngữ yêu cầu", unknown: "Chưa cung cấp",
    noMedia: "Chưa có hình ảnh gắn với hồ sơ sự kiện.", media: "Hình ảnh & nguồn gốc", mediaNote: "Đọc thông tin nguồn gốc và loại hình bên dưới mỗi hình ảnh.",
    inside: "Trong hồ sơ", understand: "Hiểu sự kiện", narrative: "Điều được ghi lại", connections: "Những nơi kết nối", context: "Con người & bối cảnh", stories: "Đọc tiếp câu chuyện", sources: "Nguồn tham chiếu",
    places: "Địa điểm liên quan", countries: "Quốc gia liên quan", relationNote: "Các mối liên hệ được ghi nhận trong hồ sơ; không mặc nhiên xác định nơi diễn ra sự kiện.", role: "Vai trò liên kết",
    noPlaces: "Chưa có địa điểm được liên kết.", noCountries: "Chưa có quốc gia được liên kết.", people: "Con người liên quan", themes: "Chủ đề", era: "Thời kỳ", territory: "Lãnh thổ lịch sử",
    noContext: "Chưa có con người, chủ đề, thời kỳ hoặc lãnh thổ lịch sử được liên kết.", contextNote: "Thông tin bối cảnh được hiển thị tại đây; trang chi tiết riêng chưa khả dụng.", relationLocale: "Ngôn ngữ và trạng thái xuất bản riêng của từng thực thể liên quan chưa được cung cấp trong hồ sơ này.",
    storiesNote: "Những câu chuyện được liên kết với sự kiện. Danh sách có thể chỉ là một phần nội dung hiện có.", noStories: "Chưa có câu chuyện được trả về cho sự kiện này.",
    supportLoading: "Đang tải nội dung…", storiesError: "Chưa tải được câu chuyện. Nội dung sự kiện vẫn có thể đọc ở trên.", sourcesError: "Chưa tải được nguồn tham chiếu. Nội dung sự kiện vẫn có thể đọc ở trên.",
    sourceIntro: "Nguồn được liên kết qua các dữ kiện đã xuất bản về sự kiện. Hồ sơ này chưa cung cấp trích dẫn cho từng đoạn văn.", noSources: "Chưa có nguồn tham chiếu được trả về.",
    sourceType: "Loại nguồn", author: "Tác giả", organization: "Tổ chức", publisher: "Nhà xuất bản", year: "Năm xuất bản", credibility: "Độ tin cậy của nguồn", sourceUntitled: "Nguồn chưa có tiêu đề", sourceUrlUnavailable: "Liên kết nguồn không khả dụng.",
    trust: "Đọc cùng bối cảnh bằng chứng", trustNote: "Độ tin cậy của nguồn không phải mức độ chắc chắn của toàn bộ sự kiện. Chưa có đánh giá mức độ chắc chắn tổng thể hoặc liên kết trích dẫn tới từng khẳng định trong hồ sơ này.",
    continue: "Tiếp tục khám phá", backStories: "Đến các câu chuyện liên quan", external: "Mở nguồn tham chiếu", unknownCredibility: "Chưa rõ",
  },
  en: {
    event: "Event", home: "Home", language: "Interface language", map: "Explore the map", breadcrumb: "Event navigation",
    loading: "Opening event profile…", missing: "Event not found", error: "Event profile unavailable", errorBody: "This profile is currently unavailable. Try again or continue exploring.", retry: "Try again",
    untitled: "No title has been supplied. The profile identifier is shown instead.", noSummary: "No summary is available for this event.", noDescription: "A detailed narrative has not been supplied.",
    date: "Historical time", unknownDate: "Date not supplied", dateNote: "Time is shown as recorded, preserving date ranges and precision.",
    fallback: "Fallback language", requested: "Requested language", unknown: "Not supplied",
    noMedia: "No imagery is linked to this event profile.", media: "Imagery & provenance", mediaNote: "Read the provenance and media classification beneath each image.",
    inside: "In this profile", understand: "Understand the event", narrative: "What is recorded", connections: "Connected places", context: "People & context", stories: "Read related stories", sources: "Reference sources",
    places: "Related places", countries: "Related countries", relationNote: "These are recorded connections. A connection does not automatically identify where the event happened.", role: "Relationship role",
    noPlaces: "No places are linked.", noCountries: "No countries are linked.", people: "Related people", themes: "Themes", era: "Historical era", territory: "Historical territory",
    noContext: "No people, themes, historical era or territory are linked.", contextNote: "Context is shown here; separate detail pages are not yet available.", relationLocale: "Individual language and publication metadata for related entities are not supplied in this profile.",
    storiesNote: "Stories linked to this event. This list may show only part of the available content.", noStories: "No stories were returned for this event.",
    supportLoading: "Loading content…", storiesError: "Related stories could not be loaded. The event remains readable above.", sourcesError: "Reference sources could not be loaded. The event remains readable above.",
    sourceIntro: "Sources linked through published facts about this event. Paragraph-level citations are not supplied in this profile.", noSources: "No reference sources were returned.",
    sourceType: "Source type", author: "Author", organization: "Organization", publisher: "Publisher", year: "Publication year", credibility: "Source credibility", sourceUntitled: "Untitled source", sourceUrlUnavailable: "The source link is unavailable.",
    trust: "Read with the evidence in context", trustNote: "Source credibility is not the certainty of the entire event. An overall confidence assessment and claim-level citation links are not supplied in this profile.",
    continue: "Continue exploring", backStories: "Go to related stories", external: "Open reference source", unknownCredibility: "Unknown",
  },
};
export type EventLocale = keyof typeof eventCopy;
