"use client";
import{useEffect,useMemo,useState}from"react";
type Block={type:string;level?:2|3|4;text?:string;attribution?:string;citationId?:string;mediaAssetId?:string;caption?:string;label?:string;entityKind?:string;entityId?:string;style?:string};
type Link={id:string;slug:string;role?:string};type Citation={id:string;source:{id:string;title:string};pageFrom?:number|null;pageTo?:number|null;locator?:string|null};
type Story={id:string;slug:string;type:string;byline?:string|null;publishedAt?:string|null;heroMedia?:{id:string;type:string;isHistorical:boolean;isAiGenerated:boolean;aiDisclosure?:string|null;accessPolicy:string;status:string}|null;places:Link[];people:Link[];events:Link[];facts:Array<{id:string;factType:string;certainty:string;editorialStatus:string}>;citations:Citation[];translation?:{title?:string;subtitle?:string|null;summary?:string|null;content?:Block[]}|null;meta:{requestedLocale:string;resolvedLocale:string;fallbackApplied:boolean}};
const API=(process.env.NEXT_PUBLIC_API_URL??"http://localhost:3000").replace(/\/$/,"");
export default function StoryExplorer({slug}:{slug:string}){const[data,setData]=useState<Story|null>(null),[error,setError]=useState(""),[loading,setLoading]=useState(true);useEffect(()=>{const c=new AbortController();fetch(`${API}/v1/stories/${encodeURIComponent(slug)}?locale=vi`,{credentials:"include",signal:c.signal}).then(async r=>{const p=await r.json();if(!r.ok)throw new Error(p?.error?.message??"Không thể tải câu chuyện.");return p?.data??p}).then(setData).catch(e=>{if(!c.signal.aborted)setError(e instanceof Error?e.message:"Không thể tải câu chuyện.")}).finally(()=>{if(!c.signal.aborted)setLoading(false)});return()=>c.abort()},[slug]);const citations=useMemo(()=>new Map((data?.citations??[]).map(x=>[x.id,x])),[data]);
 if(loading)return <main id="main" className="story-state" aria-live="polite">Đang mở câu chuyện…</main>;if(error||!data)return <main id="main" className="story-state"><div className="eyebrow">Story Explorer</div><h1>Không thể mở câu chuyện</h1><p>{error||"Không tìm thấy nội dung đã xuất bản."}</p><a className="button button-gold" href="/explore">Quay lại khám phá</a></main>;
 const t=data.translation??{},blocks=t.content??[];return <main id="main" className="story-page">
 <header className="story-hero"><div className="story-hero-inner container"><div className="eyebrow">{data.type} · Story Explorer</div><h1>{t.title??data.slug}</h1>{t.subtitle&&<p className="story-subtitle">{t.subtitle}</p>}{t.summary&&<p className="story-deck">{t.summary}</p>}<div className="story-byline">{data.byline&&<span>{data.byline}</span>}{data.publishedAt&&<time>{new Date(data.publishedAt).toLocaleDateString("vi-VN")}</time>}{data.meta.fallbackApplied&&<span>Ngôn ngữ dự phòng: {data.meta.resolvedLocale}</span>}</div>{data.heroMedia&&<MediaDisclosure media={data.heroMedia}/>}</div></header>
 <div className="story-layout container"><article className="story-reading" aria-label="Nội dung câu chuyện">{blocks.length?blocks.map((b,i)=><StoryBlock key={i} block={b} citations={citations}/>):<p className="destination-empty">Câu chuyện chưa có nội dung đã xuất bản.</p>}</article>
 <aside className="story-context"><div className="eyebrow">Connections</div><h2>Câu chuyện này kết nối với</h2><Connections title="Places" items={data.places} base="/places"/><Connections title="People" items={data.people} base="/people"/><Connections title="Events" items={data.events} base="/events"/><div className="story-trust"><strong>Evidence</strong><p>{data.facts.length} fact · {data.citations.length} citation</p></div></aside></div>
 <section className="section story-evidence"><div className="container"><div className="eyebrow">Sources & Evidence</div><h2>Nguồn đứng sau câu chuyện</h2>{data.citations.length?<div className="source-list">{data.citations.map(x=><article id={`citation-${x.id}`} key={x.id}><strong>{x.source.title}</strong><span>{[x.pageFrom&&`tr. ${x.pageFrom}`,x.pageTo&&`–${x.pageTo}`,x.locator].filter(Boolean).join(" ")}</span></article>)}</div>:<p>Chưa có citation công khai được liên kết.</p>}<div className="story-facts">{data.facts.map(x=><span key={x.id}>{x.factType} · {x.certainty}</span>)}</div></div></section></main>}
function StoryBlock({block,citations}:{block:Block;citations:Map<string,Citation>}){if(block.type==="heading"){const T=block.level===2?"h2":block.level===3?"h3":"h4";return <T>{block.text}</T>}if(block.type==="paragraph")return <p>{block.text}</p>;if(block.type==="quote")return <blockquote><p>{block.text}</p>{block.attribution&&<cite>{block.attribution}</cite>}{block.citationId&&citations.has(block.citationId)&&<a href={`#citation-${block.citationId}`}>Xem nguồn</a>}</blockquote>;if(block.type==="source_reference"){const c=block.citationId?citations.get(block.citationId):undefined;return <a className="story-source-ref" href={c?`#citation-${c.id}`:"#sources"}>{block.label??c?.source.title??"Nguồn tham chiếu"}</a>}if(block.type==="entity_reference")return <aside className="story-entity-ref"><strong>{block.entityKind}</strong><span>{block.text??"Thực thể liên quan"}</span></aside>;if(block.type==="callout")return <aside className={`story-callout ${block.style??"info"}`}>{block.text}</aside>;if(block.type==="image"||block.type==="audio")return <aside className="story-media-ref"><strong>{block.type==="image"?"Image":"Audio"}</strong><span>{block.caption??"Media được tham chiếu trong nội dung"}</span><small>Media asset: {block.mediaAssetId}</small></aside>;return null}
function Connections({title,items,base}:{title:string;items:Link[];base:string}){if(!items.length)return null;return <div className="connection-group"><strong>{title}</strong>{items.map(x=><a key={x.id} href={`${base}/${x.slug}`}>{x.slug}<small>{x.role}</small></a>)}</div>}
function MediaDisclosure({media}:{media:NonNullable<Story["heroMedia"]>}){return <div className="story-media-disclosure"><strong>{media.type}</strong>{media.isHistorical&&<span>Historical media</span>}{media.isAiGenerated&&<span>AI / Reconstruction{media.aiDisclosure?`: ${media.aiDisclosure}`:""}</span>}</div>}
