"use client";
import {FormEvent,useEffect,useState} from "react";import {restoreWebSession,webApi} from "../auth/session";
type Story={id:string;slug?:string;status?:string;moderationStatus?:string;verificationState?:string;translation?:{title?:string};translations?:Array<{title?:string}>};
export default function ContributePage(){const [stories,setStories]=useState<Story[]>([]),[auth,setAuth]=useState<boolean|undefined>(),[status,setStatus]=useState(""),[title,setTitle]=useState(""),[content,setContent]=useState("");
async function load(){const r:any=await webApi.myCommunityStories();setStories(Array.isArray(r)?r:r.items??[])}
useEffect(()=>{void restoreWebSession().then(async u=>{setAuth(Boolean(u));if(u)try{await load()}catch{setStatus("Không thể tải đóng góp của bạn.")}})},[]);
async function submit(e:FormEvent){e.preventDefault();try{setStatus("Đang gửi nội dung cộng đồng…");await webApi.createCommunityStory({type:"PERSONAL_MEMORY",translations:[{locale:"vi",title,content}]});setTitle("");setContent("");await load();setStatus("Đã gửi. Nội dung vẫn là COMMUNITY CONTENT cho tới khi quy trình phía máy chủ thay đổi trạng thái.")}catch{setStatus("Không thể gửi nội dung. Dữ liệu chưa được công bố.")}}
if(auth===false)return <main id="main" className="auth-shell"><section className="auth-card"><h1>Đóng góp ký ức</h1><a className="button button-gold" href="/auth/login">Đăng nhập để đóng góp</a></section></main>;
return <main id="main" className="content-shell"><div className="eyebrow">CONTRIBUTE · COMMUNITY CONTENT</div><h1>Ký ức cộng đồng</h1><p>Nội dung bạn gửi không tự trở thành sự thật lịch sử đã xác minh. Trạng thái kiểm duyệt/xác minh chỉ do quy trình máy chủ quyết định.</p><form className="auth-card" onSubmit={submit}><label>Tiêu đề<input required maxLength={200} value={title} onChange={e=>setTitle(e.target.value)}/></label><label>Nội dung<textarea maxLength={20000} value={content} onChange={e=>setContent(e.target.value)}/></label><button className="button button-gold">Gửi đóng góp</button></form><p role="status">{status}</p><h2>Nội dung của bạn</h2>{stories.length===0?<p>Chưa có nội dung cộng đồng.</p>:stories.map(s=><article className="content-card" key={s.id}><h3>{s.translation?.title??s.translations?.[0]?.title??"Đóng góp"}</h3><p>Kiểm duyệt: {s.moderationStatus??"chưa có trạng thái công khai"} · Xác minh: {s.verificationState??"chưa xác minh"}</p>{s.slug&&s.status==="PUBLISHED"?<a href={`/community/${s.slug}`}>Xem bản công khai</a>:<p>Chưa có liên kết chia sẻ công khai.</p>}</article>)}</main>}
