"use client";
import {useEffect,useState} from "react";
type Meta={requestedLocale:string;resolvedLocale:string;fallbackApplied:boolean};
type Place={id:string;slug:string;type:string;heroMedia?:{url?:string|null}|null;location?:{latitude:number;longitude:number}|null;translation?:{name?:string;summary?:string|null;description?:string|null}|null;currentCountry?:{slug:string;iso2:string}|null;currentRegion?:{slug:string}|null;currentCity?:{slug:string}|null;parentPlace?:{slug:string}|null;meta:Meta};
type Timeline={id:string;slug:string;title:string;date?:{display?:string}|null};
type Story={id:string;slug:string;title?:string;name?:string;summary?:string|null};
type Source={id?:string;title?:string;name?:string;url?:string;publisher?:string};
type Media={id:string;url?:string|null;alt?:string|null;caption?:string|null;provenanceType?:string;rightsStatus?:string};
type Community={id:string;slug:string;type:string;verificationState:string;title:string};
const API=(process.env.NEXT_PUBLIC_API_URL??"http://localhost:3000").replace(/\/$/,"");
async function get<T>(path:string,signal:AbortSignal){const r=await fetch(API+path,{credentials:"include",signal});const p=await r.json();if(!r.ok)throw new Error(p?.error?.message??"Không thể tải dữ liệu.");return (p?.data??p) as T}
export default function PlaceDetail({slug}:{slug:string}){
 const [place,setPlace]=useState<Place|null>(null),[timeline,setTimeline]=useState<Timeline[]>([]),[stories,setStories]=useState<Story[]>([]),[journeys,setJourneys]=useState<Story[]>([]),[sources,setSources]=useState<Source[]>([]),[media,setMedia]=useState<Media[]>([]),[community,setCommunity]=useState<Community[]>([]);const[error,setError]=useState(""),[loading,setLoading]=useState(true);
 useEffect(()=>{const c=new AbortController();setLoading(true);Promise.all([get<Place>(`/v1/places/${encodeURIComponent(slug)}?locale=vi`,c.signal),get<Timeline[]>(`/v1/places/${encodeURIComponent(slug)}/timeline?locale=vi`,c.signal),get<Story[]>(`/v1/places/${encodeURIComponent(slug)}/stories?locale=vi`,c.signal),get<Story[]>(`/v1/places/${encodeURIComponent(slug)}/journeys?locale=vi`,c.signal),get<Source[]>(`/v1/places/${encodeURIComponent(slug)}/sources`,c.signal),get<Media[]>(`/v1/places/${encodeURIComponent(slug)}/media`,c.signal),get<Community[]>(`/v1/places/${encodeURIComponent(slug)}/community?locale=vi`,c.signal)]).then(([p,t,s,j,src,m,com])=>{setPlace(p);setTimeline(t);setStories(s);setJourneys(j);setSources(src);setMedia(m);setCommunity(com)}).catch(e=>{if(!c.signal.aborted)setError(e instanceof Error?e.message:"Không thể tải địa điểm.")}).finally(()=>{if(!c.signal.aborted)setLoading(false)});return()=>c.abort()},[slug]);
 if(loading)return <main id="main" className="destination-state" aria-live="polite">Đang tải địa điểm…</main>;
 if(error||!place)return <main id="main" className="destination-state"><div className="eyebrow">Place</div><h1>Không thể mở địa điểm</h1><p>{error||"Không tìm thấy dữ liệu đã xuất bản."}</p><a className="button button-gold" href="/explore">Quay lại khám phá</a></main>;
 const t=place.translation??{};const hero=place.heroMedia?.url;
 return <main id="main" className="place-page">
  <section className="place-hero" style={hero?{backgroundImage:`linear-gradient(90deg,rgba(6,42,36,.94),rgba(6,42,36,.36)),url("${hero}")`}:undefined}><div className="container place-hero-inner"><div className="destination-breadcrumb">World → {place.currentCountry?.iso2??"Country"} → {place.currentRegion?.slug??"Region"} → {place.currentCity?.slug??"City"} → Place</div><div className="eyebrow">{place.type}</div><h1>{t.name??place.slug}</h1><p>{t.summary??"Chưa có tóm tắt đã xuất bản."}</p>{place.meta.fallbackApplied&&<span className="locale-fallback">Ngôn ngữ dự phòng: {place.meta.resolvedLocale}</span>}</div></section>
  <nav className="destination-jump container" aria-label="Đi tới nội dung địa điểm"><a href="#understand">Hiểu địa điểm</a><a href="#timeline">Dòng thời gian</a><a href="#media">Then & Now</a><a href="#stories">Câu chuyện</a><a href="#sources">Nguồn</a></nav>
  <section id="understand" className="section"><div className="container place-understand"><div><div className="eyebrow">Understand</div><h2>Một nơi, nhiều lớp thời gian</h2><p>{t.description??t.summary??"Chưa có mô tả đã xuất bản."}</p></div><aside>{place.location&&<><strong>Vị trí đã xuất bản</strong><p>{place.location.latitude.toFixed(4)}, {place.location.longitude.toFixed(4)}</p></>} {place.parentPlace&&<><strong>Thuộc địa điểm</strong><p>{place.parentPlace.slug}</p></>}</aside></div></section>
  <section id="timeline" className="section destination-dark"><div className="container"><div className="eyebrow">Time Travel</div><h2>Dòng thời gian của địa điểm</h2>{timeline.length?<div className="turning-list">{timeline.map(x=><article key={x.id}><time>{x.date?.display??"Thời gian chưa xác định"}</time><h3>{x.title}</h3></article>)}</div>:<p>Chưa có sự kiện đã xuất bản.</p>}</div></section>
  <section id="media" className="section"><div className="container"><div className="section-head"><div><div className="eyebrow">Then & Now</div><h2>Hình ảnh và dấu vết</h2></div></div>{media.length?<div className="place-media-grid">{media.map(x=><article key={x.id}>{x.url?<img src={x.url} alt={x.alt??""}/>:<div className="media-missing">Media chưa sẵn sàng</div>}<div><strong>{x.caption??"Media đã xuất bản"}</strong><small>{[x.provenanceType,x.rightsStatus].filter(Boolean).join(" · ")}</small></div></article>)}</div>:<p className="destination-empty">Chưa có media đã xuất bản.</p>}</div></section>
  <Cards id="stories" eyebrow="Story Explorer" title="Câu chuyện gắn với nơi này" items={stories} base="/stories"/>
  <Cards id="journeys" eyebrow="Journeys" title="Hành trình đi qua nơi này" items={journeys} base="/journeys"/>
  <section id="sources" className="section place-sources"><div className="container"><div className="eyebrow">Evidence & Sources</div><h2>Nguồn công khai</h2>{sources.length?<div className="source-list">{sources.map((x,i)=><article key={x.id??i}><strong>{x.title??x.name??"Nguồn tham chiếu"}</strong>{x.publisher&&<span>{x.publisher}</span>}</article>)}</div>:<p>Chưa có nguồn công khai được liên kết.</p>}</div></section>
  <section className="section"><div className="container"><div className="eyebrow">Community</div><h2>Góc nhìn từ cộng đồng</h2>{community.length?<div className="destination-card-grid">{community.map(x=><a className="destination-card" key={x.id} href={`/community/${x.slug}`}><small>{x.verificationState}</small><h3>{x.title}</h3></a>)}</div>:<p className="destination-empty">Chưa có câu chuyện cộng đồng đủ điều kiện hiển thị.</p>}</div></section>
 </main>
}
function Cards({id,eyebrow,title,items,base}:{id:string;eyebrow:string;title:string;items:Story[];base:string}){return <section id={id} className="section"><div className="container"><div className="eyebrow">{eyebrow}</div><h2>{title}</h2>{items.length?<div className="destination-card-grid">{items.map(x=><a className="destination-card" key={x.id} href={`${base}/${x.slug}`}><h3>{x.title??x.name??x.slug}</h3>{x.summary&&<p>{x.summary}</p>}</a>)}</div>:<p className="destination-empty">Chưa có nội dung đã xuất bản.</p>}</div></section>}
