/** Spec Phase 08 section 70. Spans the community/comments/reports/moderation modules, same as DISCOVERY_ERROR_CODES spans map/timeline/search/nearby. */
export const COMMUNITY_ERROR_CODES = {
  COMMUNITY_STORY_NOT_FOUND: 'COMMUNITY_STORY_NOT_FOUND',
  COMMUNITY_STORY_NOT_EDITABLE: 'COMMUNITY_STORY_NOT_EDITABLE',
  COMMUNITY_STORY_LOCKED: 'COMMUNITY_STORY_LOCKED',
  COMMUNITY_MEDIA_NOT_OWNED: 'COMMUNITY_MEDIA_NOT_OWNED',
  COMMUNITY_INVALID_ENTITY_LINK: 'COMMUNITY_INVALID_ENTITY_LINK',
  COMMUNITY_UNSAFE_CONTENT: 'COMMUNITY_UNSAFE_CONTENT',

  COMMENT_NOT_FOUND: 'COMMENT_NOT_FOUND',
  COMMENT_NOT_EDITABLE: 'COMMENT_NOT_EDITABLE',
  COMMENT_MAX_DEPTH: 'COMMENT_MAX_DEPTH',
  COMMENT_TARGET_NOT_AVAILABLE: 'COMMENT_TARGET_NOT_AVAILABLE',
  COMMENT_THREAD_LOCKED: 'COMMENT_THREAD_LOCKED',

  VOTE_SELF_NOT_ALLOWED: 'VOTE_SELF_NOT_ALLOWED',
  VOTE_TARGET_NOT_AVAILABLE: 'VOTE_TARGET_NOT_AVAILABLE',

  REPORT_DUPLICATE: 'REPORT_DUPLICATE',
  REPORT_TARGET_NOT_FOUND: 'REPORT_TARGET_NOT_FOUND',

  MODERATION_FORBIDDEN: 'MODERATION_FORBIDDEN',

  BOOKMARK_INVALID_TARGET: 'BOOKMARK_INVALID_TARGET',
} as const;
