/**
 * Machine-readable contribution/provenance error codes (Phase 09, spec
 * section 73). Same pattern as TRUST_ERROR_CODES/COMMUNITY_ERROR_CODES -
 * passed as the `code` field of a Nest HttpException, surfaced by
 * `AllExceptionsFilter` as `error.code`.
 */
export const CONTRIBUTION_ERROR_CODES = {
  CONTRIBUTION_NOT_FOUND: 'CONTRIBUTION_NOT_FOUND',
  CONTRIBUTION_NOT_EDITABLE: 'CONTRIBUTION_NOT_EDITABLE',
  CONTRIBUTION_INVALID_TRANSITION: 'CONTRIBUTION_INVALID_TRANSITION',
  CONTRIBUTION_SELF_REVIEW_FORBIDDEN: 'CONTRIBUTION_SELF_REVIEW_FORBIDDEN',
  CONTRIBUTION_REVIEW_REQUIRED: 'CONTRIBUTION_REVIEW_REQUIRED',
  CONTRIBUTION_PROVENANCE_INCOMPLETE: 'CONTRIBUTION_PROVENANCE_INCOMPLETE',
  CONTRIBUTION_RIGHTS_INCOMPLETE: 'CONTRIBUTION_RIGHTS_INCOMPLETE',
  CONTRIBUTION_ALREADY_CATALOGUED: 'CONTRIBUTION_ALREADY_CATALOGUED',
  CONTRIBUTION_CATALOGUE_NOT_ALLOWED: 'CONTRIBUTION_CATALOGUE_NOT_ALLOWED',
  CONTRIBUTION_MEDIA_NOT_OWNED: 'CONTRIBUTION_MEDIA_NOT_OWNED',
  CONTRIBUTION_INVALID_TARGET: 'CONTRIBUTION_INVALID_TARGET',
  CONTRIBUTION_VERSION_CONFLICT: 'CONTRIBUTION_VERSION_CONFLICT',
} as const;
