/**
 * Machine-readable discovery (Map/Timeline/Search/Nearby) error codes
 * (Phase 07). Same pattern as `AUTH_ERROR_CODES`/`TRUST_ERROR_CODES`/
 * `MEDIA_ERROR_CODES`/`EDITORIAL_ERROR_CODES`.
 */
export const DISCOVERY_ERROR_CODES = {
  MAP_INVALID_BBOX: 'MAP_INVALID_BBOX',
  MAP_INVALID_ZOOM: 'MAP_INVALID_ZOOM',
  MAP_INVALID_YEAR: 'MAP_INVALID_YEAR',
  MAP_RESULT_LIMIT_EXCEEDED: 'MAP_RESULT_LIMIT_EXCEEDED',
  MAP_INVALID_FILTER: 'MAP_INVALID_FILTER',

  TIMELINE_INVALID_RANGE: 'TIMELINE_INVALID_RANGE',
  TIMELINE_INVALID_FILTER: 'TIMELINE_INVALID_FILTER',
  TIMELINE_RANGE_TOO_LARGE: 'TIMELINE_RANGE_TOO_LARGE',

  SEARCH_QUERY_REQUIRED: 'SEARCH_QUERY_REQUIRED',
  SEARCH_QUERY_TOO_LONG: 'SEARCH_QUERY_TOO_LONG',
  SEARCH_INVALID_TYPE: 'SEARCH_INVALID_TYPE',

  NEARBY_INVALID_COORDINATES: 'NEARBY_INVALID_COORDINATES',
  NEARBY_INVALID_RADIUS: 'NEARBY_INVALID_RADIUS',
} as const;
