/**
 * Machine-readable Global Geography (Country/Region/City/Destination)
 * error codes (G01). Same pattern as `AUTH_ERROR_CODES`/`TRUST_ERROR_CODES`/
 * `MEDIA_ERROR_CODES`/`DISCOVERY_ERROR_CODES`/`EDITORIAL_ERROR_CODES`.
 */
export const GEOGRAPHY_ERROR_CODES = {
  COUNTRY_NOT_FOUND: 'COUNTRY_NOT_FOUND',
  COUNTRY_ISO_CONFLICT: 'COUNTRY_ISO_CONFLICT',

  REGION_NOT_FOUND: 'REGION_NOT_FOUND',
  REGION_PARENT_NOT_FOUND: 'REGION_PARENT_NOT_FOUND',
  REGION_PARENT_CYCLE: 'REGION_PARENT_CYCLE',
  REGION_PARENT_COUNTRY_MISMATCH: 'REGION_PARENT_COUNTRY_MISMATCH',

  CITY_NOT_FOUND: 'CITY_NOT_FOUND',
  CITY_INVALID_TIMEZONE: 'CITY_INVALID_TIMEZONE',

  DESTINATION_NOT_FOUND: 'DESTINATION_NOT_FOUND',

  GEOGRAPHY_COUNTRY_MISMATCH: 'GEOGRAPHY_COUNTRY_MISMATCH',
  GEOGRAPHY_REGION_CITY_MISMATCH: 'GEOGRAPHY_REGION_CITY_MISMATCH',
  GEOGRAPHY_CANNOT_PUBLISH_WITHOUT_TRANSLATION: 'GEOGRAPHY_CANNOT_PUBLISH_WITHOUT_TRANSLATION',
} as const;
