/**
 * Machine-readable Knowledge & Place Data Ingestion (G06.5) error codes.
 * Same pattern as PROVIDER_ERROR_CODES/TRIP_ERROR_CODES/etc.
 */
export const INGESTION_ERROR_CODES = {
  INGESTION_SOURCE_NOT_FOUND: 'INGESTION_SOURCE_NOT_FOUND',
  INGESTION_SOURCE_CODE_CONFLICT: 'INGESTION_SOURCE_CODE_CONFLICT',
  INGESTION_SOURCE_DISABLED: 'INGESTION_SOURCE_DISABLED',

  INGESTION_POLICY_NOT_FOUND: 'INGESTION_POLICY_NOT_FOUND',
  INGESTION_POLICY_DISABLED: 'INGESTION_POLICY_DISABLED',
  INGESTION_POLICY_RIGHT_UNKNOWN: 'INGESTION_POLICY_RIGHT_UNKNOWN',
  INGESTION_POLICY_RIGHT_PROHIBITED: 'INGESTION_POLICY_RIGHT_PROHIBITED',
  INGESTION_POLICY_CONDITIONAL_UNMET: 'INGESTION_POLICY_CONDITIONAL_UNMET',
  INGESTION_POLICY_STORAGE_PROHIBITED: 'INGESTION_POLICY_STORAGE_PROHIBITED',
  INGESTION_POLICY_NO_CREDENTIAL: 'INGESTION_POLICY_NO_CREDENTIAL',

  INGESTION_JOB_NOT_FOUND: 'INGESTION_JOB_NOT_FOUND',
  INGESTION_JOB_SCOPE_UNBOUNDED: 'INGESTION_JOB_SCOPE_UNBOUNDED',

  INGESTION_RUN_NOT_FOUND: 'INGESTION_RUN_NOT_FOUND',
  INGESTION_RUN_NOT_CANCELLABLE: 'INGESTION_RUN_NOT_CANCELLABLE',
  INGESTION_RUN_ALREADY_TERMINAL: 'INGESTION_RUN_ALREADY_TERMINAL',

  INGESTION_ADAPTER_NOT_IMPLEMENTED: 'INGESTION_ADAPTER_NOT_IMPLEMENTED',
  INGESTION_ADAPTER_FETCH_FAILED: 'INGESTION_ADAPTER_FETCH_FAILED',
  INGESTION_OUTBOUND_URL_REJECTED: 'INGESTION_OUTBOUND_URL_REJECTED',
  INGESTION_OUTBOUND_RESPONSE_TOO_LARGE: 'INGESTION_OUTBOUND_RESPONSE_TOO_LARGE',

  INGESTION_CANDIDATE_NOT_FOUND: 'INGESTION_CANDIDATE_NOT_FOUND',
  INGESTION_CANDIDATE_INVALID_TRANSITION: 'INGESTION_CANDIDATE_INVALID_TRANSITION',
  INGESTION_CANDIDATE_NOT_REVIEWABLE: 'INGESTION_CANDIDATE_NOT_REVIEWABLE',
  INGESTION_CANDIDATE_RESOLUTION_REQUIRED: 'INGESTION_CANDIDATE_RESOLUTION_REQUIRED',
  INGESTION_CANDIDATE_SELF_APPROVAL_FORBIDDEN: 'INGESTION_CANDIDATE_SELF_APPROVAL_FORBIDDEN',

  INGESTION_RESOLUTION_AMBIGUOUS: 'INGESTION_RESOLUTION_AMBIGUOUS',
  INGESTION_RESOLUTION_CONFLICT: 'INGESTION_RESOLUTION_CONFLICT',

  INGESTION_PROMOTION_MISSING_EVIDENCE: 'INGESTION_PROMOTION_MISSING_EVIDENCE',
  INGESTION_PROMOTION_MEDIA_RIGHTS_UNVERIFIED: 'INGESTION_PROMOTION_MEDIA_RIGHTS_UNVERIFIED',
  INGESTION_PROMOTION_TYPE_UNSUPPORTED: 'INGESTION_PROMOTION_TYPE_UNSUPPORTED',
} as const;
