/**
 * Machine-readable Provider + Licensing (G02) error codes. Same pattern as
 * `AUTH_ERROR_CODES`/`TRUST_ERROR_CODES`/`GEOGRAPHY_ERROR_CODES`/etc.
 */
export const PROVIDER_ERROR_CODES = {
  PROVIDER_NOT_FOUND: 'PROVIDER_NOT_FOUND',
  PROVIDER_CODE_CONFLICT: 'PROVIDER_CODE_CONFLICT',
  PROVIDER_NOT_ACTIVE: 'PROVIDER_NOT_ACTIVE',

  PROVIDER_CAPABILITY_UNSUPPORTED: 'PROVIDER_CAPABILITY_UNSUPPORTED',
  PROVIDER_CAPABILITY_NOT_ENABLED: 'PROVIDER_CAPABILITY_NOT_ENABLED',
  PROVIDER_CAPABILITY_ALREADY_DECLARED: 'PROVIDER_CAPABILITY_ALREADY_DECLARED',

  PROVIDER_INTEGRATION_NOT_FOUND: 'PROVIDER_INTEGRATION_NOT_FOUND',
  PROVIDER_INTEGRATION_NOT_CONFIGURED: 'PROVIDER_INTEGRATION_NOT_CONFIGURED',
  PROVIDER_INTEGRATION_SUSPENDED: 'PROVIDER_INTEGRATION_SUSPENDED',
  PROVIDER_INTEGRATION_ALREADY_EXISTS: 'PROVIDER_INTEGRATION_ALREADY_EXISTS',
  PROVIDER_CREDENTIALS_MISSING: 'PROVIDER_CREDENTIALS_MISSING',

  PROVIDER_LICENSE_NOT_FOUND: 'PROVIDER_LICENSE_NOT_FOUND',
  PROVIDER_LICENSE_NOT_APPROVED: 'PROVIDER_LICENSE_NOT_APPROVED',
  PROVIDER_LICENSE_EXPIRED: 'PROVIDER_LICENSE_EXPIRED',
  PROVIDER_LICENSE_REVOKED: 'PROVIDER_LICENSE_REVOKED',
  PROVIDER_LICENSE_NOT_REVIEWED: 'PROVIDER_LICENSE_NOT_REVIEWED',
  PROVIDER_LICENSE_CONDITIONAL_NOTES_REQUIRED: 'PROVIDER_LICENSE_CONDITIONAL_NOTES_REQUIRED',
  PROVIDER_LICENSE_INVALID_TRANSITION: 'PROVIDER_LICENSE_INVALID_TRANSITION',

  PROVIDER_USAGE_NOT_ALLOWED: 'PROVIDER_USAGE_NOT_ALLOWED',
  PROVIDER_ATTRIBUTION_REQUIRED: 'PROVIDER_ATTRIBUTION_REQUIRED',
  PROVIDER_POLICY_UNKNOWN: 'PROVIDER_POLICY_UNKNOWN',
  PROVIDER_DATA_POLICY_NOT_FOUND: 'PROVIDER_DATA_POLICY_NOT_FOUND',
} as const;
