/**
 * Machine-readable Stay + Food + Activities (G05) error codes. Same pattern
 * as `GEOGRAPHY_ERROR_CODES`/`PROVIDER_ERROR_CODES`/etc. Provider gate
 * failures (license/attribution/capability) reuse `PROVIDER_ERROR_CODES`
 * directly - never duplicated here.
 */
export const STAY_FOOD_ACTIVITY_ERROR_CODES = {
  ACCOMMODATION_NOT_FOUND: 'ACCOMMODATION_NOT_FOUND',
  RESTAURANT_NOT_FOUND: 'RESTAURANT_NOT_FOUND',
  ACTIVITY_NOT_FOUND: 'ACTIVITY_NOT_FOUND',
  ATTRACTION_NOT_FOUND: 'ATTRACTION_NOT_FOUND',
  ATTRACTION_PLACE_NOT_FOUND: 'ATTRACTION_PLACE_NOT_FOUND',
  CUISINE_NOT_FOUND: 'CUISINE_NOT_FOUND',
  DISH_NOT_FOUND: 'DISH_NOT_FOUND',

  PROVIDER_REFERENCE_NOT_FOUND: 'SFA_PROVIDER_REFERENCE_NOT_FOUND',
  PROVIDER_REFERENCE_ALREADY_MAPPED: 'SFA_PROVIDER_REFERENCE_ALREADY_MAPPED',

  OFFER_NOT_FOUND: 'SFA_OFFER_NOT_FOUND',
  OFFER_CONTEXT_INVALID: 'SFA_OFFER_CONTEXT_INVALID',

  INVALID_DATE_RANGE: 'SFA_INVALID_DATE_RANGE',
  INVALID_OCCUPANCY: 'SFA_INVALID_OCCUPANCY',
  INVALID_CURRENCY: 'SFA_INVALID_CURRENCY',
} as const;
