/**
 * Machine-readable Trip Planner + Cost Engine (G06) error codes. Same
 * pattern as `GEOGRAPHY_ERROR_CODES`/`PROVIDER_ERROR_CODES`/
 * `STAY_FOOD_ACTIVITY_ERROR_CODES`. Provider gate failures (license/
 * attribution/capability) reuse `PROVIDER_ERROR_CODES` directly - never
 * duplicated here. `TRIP_VERSION_CONFLICT` is served as HTTP 409 (a
 * deliberate divergence from Story/Journey/Contribution's existing 400 for
 * the same optimistic-concurrency shape - see
 * docs/backend/G06_PRE_IMPLEMENTATION_REPORT.md section 1.7).
 */
export const TRIP_ERROR_CODES = {
  TRIP_NOT_FOUND: 'TRIP_NOT_FOUND',
  TRIP_NOT_OWNER: 'TRIP_NOT_OWNER',
  TRIP_VERSION_CONFLICT: 'TRIP_VERSION_CONFLICT',
  TRIP_INVALID_DATE_RANGE: 'TRIP_INVALID_DATE_RANGE',
  TRIP_INVALID_CURRENCY: 'TRIP_INVALID_CURRENCY',
  // An archived Trip is not an active planning Trip (spec correction, see
  // pre-implementation report section 3.8/7) - every itinerary/transport/
  // estimate mutation route rejects with this once `Trip.archivedAt` is set.
  TRIP_ARCHIVED: 'TRIP_ARCHIVED',

  TRIP_DESTINATION_NOT_FOUND: 'TRIP_DESTINATION_NOT_FOUND',
  TRIP_DESTINATION_INVALID_DATE_RANGE: 'TRIP_DESTINATION_INVALID_DATE_RANGE',
  TRIP_DESTINATION_OUT_OF_TRIP_RANGE: 'TRIP_DESTINATION_OUT_OF_TRIP_RANGE',

  TRIP_DAY_NOT_FOUND: 'TRIP_DAY_NOT_FOUND',
  TRIP_DAY_OUT_OF_TRIP_RANGE: 'TRIP_DAY_OUT_OF_TRIP_RANGE',

  TRIP_ITEM_NOT_FOUND: 'TRIP_ITEM_NOT_FOUND',
  TRIP_ITEM_TARGET_MISMATCH: 'TRIP_ITEM_TARGET_MISMATCH',
  TRIP_ITEM_TARGET_REQUIRED: 'TRIP_ITEM_TARGET_REQUIRED',
  TRIP_ITEM_TARGET_NOT_PUBLISHED: 'TRIP_ITEM_TARGET_NOT_PUBLISHED',
  TRIP_ITEM_PLACE_NOT_FOUND: 'TRIP_ITEM_PLACE_NOT_FOUND',
  TRIP_ITEM_REORDER_INVALID: 'TRIP_ITEM_REORDER_INVALID',

  TRIP_TRANSPORT_LEG_NOT_FOUND: 'TRIP_TRANSPORT_LEG_NOT_FOUND',
  TRIP_TRANSPORT_LEG_IN_USE: 'TRIP_TRANSPORT_LEG_IN_USE',

  COST_ASSUMPTION_NOT_FOUND: 'COST_ASSUMPTION_NOT_FOUND',
  COST_ASSUMPTION_INVALID_RANGE: 'COST_ASSUMPTION_INVALID_RANGE',
  COST_ASSUMPTION_INVALID_EFFECTIVE_RANGE: 'COST_ASSUMPTION_INVALID_EFFECTIVE_RANGE',
  COST_ASSUMPTION_INVALID_STATUS_TRANSITION: 'COST_ASSUMPTION_INVALID_STATUS_TRANSITION',
  COST_ASSUMPTION_SCOPE_MISMATCH: 'COST_ASSUMPTION_SCOPE_MISMATCH',
  COST_ASSUMPTION_DUPLICATE_IDENTITY: 'COST_ASSUMPTION_DUPLICATE_IDENTITY',

  ESTIMATE_GENERATION_NOT_FOUND: 'ESTIMATE_GENERATION_NOT_FOUND',
  ESTIMATE_GENERATION_FAILED: 'ESTIMATE_GENERATION_FAILED',
} as const;
