"use client";
import {FormEvent,useEffect,useState} from "react";
import {useParams} from "next/navigation";
import {webApi} from "../../../auth/session";
type Detail={slug:string;translation?:{name?:string;summary?:string}};
type Offer={providerCode:string;currency:string;amount:string;availability:string;durationMinutes?:number|null;attribution?:{displayText?:string|null}};
export default function Activity(){const {slug}=useParams<{slug:string}>();const [d,setD]=useState<Detail>();const [offers,setOffers]=useState<Offer[]>([]);const [status,setStatus]=useState("Đang tải hoạt động…");const [busy,setBusy]=useState(false);
useEffect(()=>{webApi.activity<Detail>(slug).then(x=>{setD(x);setStatus("")}).catch(()=>setStatus("Không thể tải hoạt động này."))},[slug]);
async function search(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setOffers([]);const f=new FormData(e.currentTarget);try{const r=await webApi.activityOffers<{offers:Offer[]}>(slug,{date:String(f.get("date")),participants:Number(f.get("participants")),currency:String(f.get("currency")).toUpperCase()});setOffers(r.offers);setStatus(r.offers.length?"":"Không có ưu đãi hoạt động hiện tại đủ điều kiện.")}catch{setStatus("Không thể lấy dữ liệu nhà cung cấp. Dấu Việt không suy đoán giá hoặc khả dụng.")}finally{setBusy(false)}}
return <main id="main" className="auth-shell"><section className="auth-card"><div className="eyebrow">BOOK · ACTIVITY</div><h1>{d?.translation?.name??slug}</h1>{d?.translation?.summary&&<p>{d.translation.summary}</p>}<form className="auth-form" onSubmit={search}><label>Ngày<input name="date" type="date" required/></label><label>Số người<input name="participants" type="number" min="1" defaultValue="2" required/></label><label>Tiền tệ<input name="currency" pattern="[A-Za-z]{3}" defaultValue="VND" required/></label><button className="button button-gold" disabled={busy}>{busy?"Đang kiểm tra…":"Kiểm tra hoạt động"}</button></form><p role="status">{status}</p>{offers.map((o,i)=><article key={i}><h2>{o.providerCode}</h2><p>{o.amount} {o.currency} · {o.availability}{o.durationMinutes?" · "+o.durationMinutes+" phút":""}</p>{o.attribution?.displayText&&<p>{o.attribution.displayText}</p>}<p>Dữ liệu nhà cung cấp hiện tại; đây không phải xác nhận đặt chỗ.</p></article>)}</section></main>}