/**
 * Machine-readable auth error codes (spec Phase 02 section 30). These are
 * passed as the `code` field of Nest's HttpException response body, which
 * `AllExceptionsFilter` surfaces as `error.code` in the response envelope -
 * never a raw stack trace, never a secret value.
 */
export const AUTH_ERROR_CODES = {
  INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  EMAIL_NOT_VERIFIED: 'AUTH_EMAIL_NOT_VERIFIED',
  EMAIL_ALREADY_REGISTERED: 'AUTH_EMAIL_ALREADY_REGISTERED',
  SESSION_EXPIRED: 'AUTH_SESSION_EXPIRED',
  SESSION_REVOKED: 'AUTH_SESSION_REVOKED',
  ACCOUNT_SUSPENDED: 'AUTH_ACCOUNT_SUSPENDED',
  ACCOUNT_DISABLED: 'AUTH_ACCOUNT_DISABLED',
  FORBIDDEN: 'AUTH_FORBIDDEN',
  RATE_LIMITED: 'AUTH_RATE_LIMITED',
  TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
  TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  TOKEN_ALREADY_USED: 'AUTH_TOKEN_ALREADY_USED',
  REFRESH_REUSE_DETECTED: 'AUTH_REFRESH_REUSE_DETECTED',
  REFRESH_TOKEN_MISSING: 'AUTH_REFRESH_TOKEN_MISSING',
  CSRF_INVALID: 'AUTH_CSRF_INVALID',
} as const;
