import {expect,test,type Page} from "@playwright/test";
async function json(r:any,body:any,status=200){await r.fulfill({status,contentType:"application/json",body:JSON.stringify({data:body})})}
async function setup(page:Page,roles:string[]){await page.route("**/v1/auth/refresh",r=>json(r,{accessToken:"token",expiresIn:900}));await page.route("**/v1/users/me",r=>json(r,{id:"u1",email:"admin@example.com",roles}));}
test("EDITOR sees review/editorial/media but not moderation or admin-only operations",async({page})=>{await setup(page,["EDITOR"]);await page.goto("/");await expect(page.getByRole("link",{name:"Contribution review"})).toBeVisible();await expect(page.getByRole("link",{name:"Editorial / trust"})).toBeVisible();await expect(page.getByRole("link",{name:"Media / provenance"})).toBeVisible();await expect(page.getByRole("link",{name:"Moderation"})).toHaveCount(0);await expect(page.getByRole("link",{name:"Ingestion / provider"})).toHaveCount(0);await expect(page.getByRole("link",{name:"Operations / affiliate"})).toHaveCount(0)});
test("HISTORIAN_REVIEWER sees review/cataloguing surfaces but not moderator/admin-only workspaces",async({page})=>{await setup(page,["HISTORIAN_REVIEWER"]);await page.goto("/");await expect(page.getByRole("link",{name:"Contribution review"})).toBeVisible();await expect(page.getByRole("link",{name:"Media / provenance"})).toBeVisible();await expect(page.getByRole("link",{name:"Moderation"})).toHaveCount(0);await expect(page.getByRole("link",{name:"Ingestion / provider"})).toHaveCount(0)});
test("MODERATOR sees moderation but not editorial review or ingestion",async({page})=>{await setup(page,["MODERATOR"]);await page.goto("/");await expect(page.getByRole("link",{name:"Moderation"})).toBeVisible();await expect(page.getByRole("link",{name:"Contribution review"})).toHaveCount(0);await expect(page.getByRole("link",{name:"Editorial / trust"})).toHaveCount(0);await expect(page.getByRole("link",{name:"Ingestion / provider"})).toHaveCount(0)});
test("ADMIN sees every Phase 6 workspace",async({page})=>{await setup(page,["ADMIN"]);await page.goto("/");for(const name of ["Contribution review","Editorial / trust","Media / provenance","Moderation","Ingestion / provider","Operations / affiliate"])await expect(page.getByRole("link",{name})).toBeVisible()});
test("non-admin role is rejected by the admin gate",async({page})=>{await setup(page,["CONTRIBUTOR"]);await page.goto("/");await expect(page.getByRole("heading",{name:"Yêu cầu quyền quản trị"})).toBeVisible()});
test("contribution detail preserves provenance trust disclosure and catalogue lock for EDITOR",async({page})=>{await setup(page,["EDITOR"]);await page.route("**/v1/admin/contributions/c1",r=>json(r,{id:"c1",version:3,title:"Ảnh gia đình",type:"PHOTO",status:"SUBMITTED",provenanceEvidence:[{id:"p1",referenceType:"OTHER",sourceOrganization:"Gia đình"}]}));await page.goto("/contributions/c1");await expect(page.getByText("Đây là evidence đầu vào; không phải canonical Source hay Historical Fact")).toBeVisible();await expect(page.getByText("Cataloguing bị khóa: chỉ HISTORIAN_REVIEWER hoặc ADMIN.")).toBeVisible()});
